// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: google/rpc/status.proto
#ifndef GRPC_google_2frpc_2fstatus_2eproto__INCLUDED
#define GRPC_google_2frpc_2fstatus_2eproto__INCLUDED

#include "google/rpc/status.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace google {
namespace rpc {

}  // namespace rpc
}  // namespace google


#endif  // GRPC_google_2frpc_2fstatus_2eproto__INCLUDED
