// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: dm_env_rpc.proto

#include "dm_env_rpc.pb.h"
#include "dm_env_rpc.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace dm_env_rpc {
namespace v1 {

static const char* Environment_method_names[] = {
  "/dm_env_rpc.v1.Environment/Process",
};

std::unique_ptr< Environment::Stub> Environment::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Environment::Stub> stub(new Environment::Stub(channel, options));
  return stub;
}

Environment::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Process_(Environment_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::dm_env_rpc::v1::EnvironmentRequest, ::dm_env_rpc::v1::EnvironmentResponse>* Environment::Stub::ProcessRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::dm_env_rpc::v1::EnvironmentRequest, ::dm_env_rpc::v1::EnvironmentResponse>::Create(channel_.get(), rpcmethod_Process_, context);
}

void Environment::Stub::async::Process(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::dm_env_rpc::v1::EnvironmentRequest,::dm_env_rpc::v1::EnvironmentResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::dm_env_rpc::v1::EnvironmentRequest,::dm_env_rpc::v1::EnvironmentResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_Process_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::dm_env_rpc::v1::EnvironmentRequest, ::dm_env_rpc::v1::EnvironmentResponse>* Environment::Stub::AsyncProcessRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::dm_env_rpc::v1::EnvironmentRequest, ::dm_env_rpc::v1::EnvironmentResponse>::Create(channel_.get(), cq, rpcmethod_Process_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::dm_env_rpc::v1::EnvironmentRequest, ::dm_env_rpc::v1::EnvironmentResponse>* Environment::Stub::PrepareAsyncProcessRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::dm_env_rpc::v1::EnvironmentRequest, ::dm_env_rpc::v1::EnvironmentResponse>::Create(channel_.get(), cq, rpcmethod_Process_, context, false, nullptr);
}

Environment::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Environment_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< Environment::Service, ::dm_env_rpc::v1::EnvironmentRequest, ::dm_env_rpc::v1::EnvironmentResponse>(
          [](Environment::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::dm_env_rpc::v1::EnvironmentResponse,
             ::dm_env_rpc::v1::EnvironmentRequest>* stream) {
               return service->Process(ctx, stream);
             }, this)));
}

Environment::Service::~Service() {
}

::grpc::Status Environment::Service::Process(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::dm_env_rpc::v1::EnvironmentResponse, ::dm_env_rpc::v1::EnvironmentRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace dm_env_rpc
}  // namespace v1

