// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: urlab_dm_env_rpc.proto

#include "urlab_dm_env_rpc.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace urlab {
namespace dm_env_rpc {
namespace v1 {

inline constexpr UrlabPacket::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        op_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        status_{nullptr},
        sequence_id_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR UrlabPacket::UrlabPacket(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct UrlabPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UrlabPacketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UrlabPacketDefaultTypeInternal() {}
  union {
    UrlabPacket _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UrlabPacketDefaultTypeInternal _UrlabPacket_default_instance_;
}  // namespace v1
}  // namespace dm_env_rpc
}  // namespace urlab
static ::_pb::Metadata file_level_metadata_urlab_5fdm_5fenv_5frpc_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_urlab_5fdm_5fenv_5frpc_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_urlab_5fdm_5fenv_5frpc_2eproto = nullptr;
const ::uint32_t TableStruct_urlab_5fdm_5fenv_5frpc_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::urlab::dm_env_rpc::v1::UrlabPacket, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::urlab::dm_env_rpc::v1::UrlabPacket, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::urlab::dm_env_rpc::v1::UrlabPacket, _impl_.op_),
    PROTOBUF_FIELD_OFFSET(::urlab::dm_env_rpc::v1::UrlabPacket, _impl_.payload_),
    PROTOBUF_FIELD_OFFSET(::urlab::dm_env_rpc::v1::UrlabPacket, _impl_.sequence_id_),
    PROTOBUF_FIELD_OFFSET(::urlab::dm_env_rpc::v1::UrlabPacket, _impl_.status_),
    ~0u,
    ~0u,
    ~0u,
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 12, -1, sizeof(::urlab::dm_env_rpc::v1::UrlabPacket)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::urlab::dm_env_rpc::v1::_UrlabPacket_default_instance_._instance,
};
const char descriptor_table_protodef_urlab_5fdm_5fenv_5frpc_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\026urlab_dm_env_rpc.proto\022\023urlab.dm_env_r"
    "pc.v1\032\027google/rpc/status.proto\"c\n\013UrlabP"
    "acket\022\n\n\002op\030\001 \001(\t\022\017\n\007payload\030\002 \001(\014\022\023\n\013se"
    "quence_id\030\003 \001(\003\022\"\n\006status\030\004 \001(\0132\022.google"
    ".rpc.Statusb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_urlab_5fdm_5fenv_5frpc_2eproto_deps[1] =
    {
        &::descriptor_table_google_2frpc_2fstatus_2eproto,
};
static ::absl::once_flag descriptor_table_urlab_5fdm_5fenv_5frpc_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_urlab_5fdm_5fenv_5frpc_2eproto = {
    false,
    false,
    179,
    descriptor_table_protodef_urlab_5fdm_5fenv_5frpc_2eproto,
    "urlab_dm_env_rpc.proto",
    &descriptor_table_urlab_5fdm_5fenv_5frpc_2eproto_once,
    descriptor_table_urlab_5fdm_5fenv_5frpc_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_urlab_5fdm_5fenv_5frpc_2eproto::offsets,
    file_level_metadata_urlab_5fdm_5fenv_5frpc_2eproto,
    file_level_enum_descriptors_urlab_5fdm_5fenv_5frpc_2eproto,
    file_level_service_descriptors_urlab_5fdm_5fenv_5frpc_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_urlab_5fdm_5fenv_5frpc_2eproto_getter() {
  return &descriptor_table_urlab_5fdm_5fenv_5frpc_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_urlab_5fdm_5fenv_5frpc_2eproto(&descriptor_table_urlab_5fdm_5fenv_5frpc_2eproto);
namespace urlab {
namespace dm_env_rpc {
namespace v1 {
// ===================================================================

class UrlabPacket::_Internal {
 public:
  using HasBits = decltype(std::declval<UrlabPacket>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(UrlabPacket, _impl_._has_bits_);
  static const ::google::rpc::Status& status(const UrlabPacket* msg);
  static void set_has_status(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::google::rpc::Status& UrlabPacket::_Internal::status(const UrlabPacket* msg) {
  return *msg->_impl_.status_;
}
void UrlabPacket::clear_status() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.status_ != nullptr) _impl_.status_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
UrlabPacket::UrlabPacket(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:urlab.dm_env_rpc.v1.UrlabPacket)
}
inline PROTOBUF_NDEBUG_INLINE UrlabPacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        op_(arena, from.op_),
        payload_(arena, from.payload_) {}

UrlabPacket::UrlabPacket(
    ::google::protobuf::Arena* arena,
    const UrlabPacket& from)
    : ::google::protobuf::Message(arena) {
  UrlabPacket* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.status_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::google::rpc::Status>(arena, *from._impl_.status_)
                : nullptr;
  _impl_.sequence_id_ = from._impl_.sequence_id_;

  // @@protoc_insertion_point(copy_constructor:urlab.dm_env_rpc.v1.UrlabPacket)
}
inline PROTOBUF_NDEBUG_INLINE UrlabPacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        op_(arena),
        payload_(arena) {}

inline void UrlabPacket::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, status_),
           0,
           offsetof(Impl_, sequence_id_) -
               offsetof(Impl_, status_) +
               sizeof(Impl_::sequence_id_));
}
UrlabPacket::~UrlabPacket() {
  // @@protoc_insertion_point(destructor:urlab.dm_env_rpc.v1.UrlabPacket)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UrlabPacket::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.op_.Destroy();
  _impl_.payload_.Destroy();
  delete _impl_.status_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void UrlabPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:urlab.dm_env_rpc.v1.UrlabPacket)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.op_.ClearToEmpty();
  _impl_.payload_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.status_ != nullptr);
    _impl_.status_->Clear();
  }
  _impl_.sequence_id_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* UrlabPacket::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 42, 2> UrlabPacket::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(UrlabPacket, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_UrlabPacket_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .google.rpc.Status status = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 0, 0, PROTOBUF_FIELD_OFFSET(UrlabPacket, _impl_.status_)}},
    // string op = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UrlabPacket, _impl_.op_)}},
    // bytes payload = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(UrlabPacket, _impl_.payload_)}},
    // int64 sequence_id = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(UrlabPacket, _impl_.sequence_id_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(UrlabPacket, _impl_.sequence_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string op = 1;
    {PROTOBUF_FIELD_OFFSET(UrlabPacket, _impl_.op_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes payload = 2;
    {PROTOBUF_FIELD_OFFSET(UrlabPacket, _impl_.payload_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // int64 sequence_id = 3;
    {PROTOBUF_FIELD_OFFSET(UrlabPacket, _impl_.sequence_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // .google.rpc.Status status = 4;
    {PROTOBUF_FIELD_OFFSET(UrlabPacket, _impl_.status_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::rpc::Status>()},
  }}, {{
    "\37\2\0\0\0\0\0\0"
    "urlab.dm_env_rpc.v1.UrlabPacket"
    "op"
  }},
};

::uint8_t* UrlabPacket::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:urlab.dm_env_rpc.v1.UrlabPacket)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string op = 1;
  if (!this->_internal_op().empty()) {
    const std::string& _s = this->_internal_op();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "urlab.dm_env_rpc.v1.UrlabPacket.op");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // bytes payload = 2;
  if (!this->_internal_payload().empty()) {
    const std::string& _s = this->_internal_payload();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  // int64 sequence_id = 3;
  if (this->_internal_sequence_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<3>(
            stream, this->_internal_sequence_id(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .google.rpc.Status status = 4;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, _Internal::status(this),
        _Internal::status(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:urlab.dm_env_rpc.v1.UrlabPacket)
  return target;
}

::size_t UrlabPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:urlab.dm_env_rpc.v1.UrlabPacket)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string op = 1;
  if (!this->_internal_op().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_op());
  }

  // bytes payload = 2;
  if (!this->_internal_payload().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_payload());
  }

  // .google.rpc.Status status = 4;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.status_);
  }

  // int64 sequence_id = 3;
  if (this->_internal_sequence_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_sequence_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData UrlabPacket::_class_data_ = {
    UrlabPacket::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* UrlabPacket::GetClassData() const {
  return &_class_data_;
}

void UrlabPacket::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<UrlabPacket*>(&to_msg);
  auto& from = static_cast<const UrlabPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:urlab.dm_env_rpc.v1.UrlabPacket)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_op().empty()) {
    _this->_internal_set_op(from._internal_op());
  }
  if (!from._internal_payload().empty()) {
    _this->_internal_set_payload(from._internal_payload());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_status()->::google::rpc::Status::MergeFrom(
        from._internal_status());
  }
  if (from._internal_sequence_id() != 0) {
    _this->_internal_set_sequence_id(from._internal_sequence_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UrlabPacket::CopyFrom(const UrlabPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:urlab.dm_env_rpc.v1.UrlabPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool UrlabPacket::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* UrlabPacket::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void UrlabPacket::InternalSwap(UrlabPacket* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.op_, &other->_impl_.op_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.payload_, &other->_impl_.payload_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UrlabPacket, _impl_.sequence_id_)
      + sizeof(UrlabPacket::_impl_.sequence_id_)
      - PROTOBUF_FIELD_OFFSET(UrlabPacket, _impl_.status_)>(
          reinterpret_cast<char*>(&_impl_.status_),
          reinterpret_cast<char*>(&other->_impl_.status_));
}

::google::protobuf::Metadata UrlabPacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_urlab_5fdm_5fenv_5frpc_2eproto_getter, &descriptor_table_urlab_5fdm_5fenv_5frpc_2eproto_once,
      file_level_metadata_urlab_5fdm_5fenv_5frpc_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace dm_env_rpc
}  // namespace urlab
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
