// Copyright (c) 2026 Jonathan Embley-Riches. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "Transport/ShmPublishTransport.h"
#include "Bridge/RpcDispatcher.h"
#include "MuJoCo/Core/AMjManager.h"
#include "Misc/Paths.h"
#include "HAL/FileManager.h"
#include "HAL/PlatformProcess.h"
#include "Utils/URLabLogging.h"

void UURLabShmPublishTransport::SetOwningManager(AAMjManager* InMgr)
{
	OwningManager = InMgr;
}

FString UURLabShmPublishTransport::ResolveSessionDir(const FString& InSessionId)
{
	const FString Sid = InSessionId.IsEmpty() ? TEXT("live") : InSessionId;
	return FPaths::Combine(FPaths::ProjectSavedDir(), TEXT("URLabShm"), Sid);
}

FString UURLabShmPublishTransport::MakeInstanceSessionId(const FString& BaseSid,
	int32 InstancePort)
{
	// Mirror UURLabShmRpcTransport::TransportInit verbatim so the state/camera
	// segments derive their per-instance identity the same way the RPC segment
	// does. The pid makes the name unique per editor process; the port, when
	// supplied, keeps it traceable to the instance.
	const FString Base = BaseSid.IsEmpty() ? FString(TEXT("live")) : BaseSid;
	const uint32 Pid = FPlatformProcess::GetCurrentProcessId();
	return InstancePort > 0
			   ? FString::Printf(TEXT("%s_p%d_%u"), *Base, InstancePort, Pid)
			   : FString::Printf(TEXT("%s_%u"), *Base, Pid);
}

FString UURLabShmPublishTransport::ResolveActiveSessionBase(AAMjManager* Mgr)
{
	FString Sid;
	if (FURLabRpcDispatcher* Disp = Mgr ? Mgr->GetStepDispatcher() : nullptr)
	{
		Sid = Disp->GetActiveSessionId();
	}
	if (Sid.IsEmpty())
		Sid = TEXT("live");
	return Sid;
}

bool UURLabShmPublishTransport::TransportInit()
{
	AAMjManager* Mgr = OwningManager.Get();
	if (!Mgr || !Mgr->PhysicsEngine)
	{
		UE_LOG(LogURLabNet, Warning,
			TEXT("UURLabShmPublishTransport: no manager / engine -- skipping init"));
		return false;
	}

	// Resolve the session directory. Honour an explicit SessionId set in
	// editor; otherwise mirror the dispatcher's session id once it has
	// been generated by the first hello, otherwise fall back to "live".
	// ResolveActiveSessionBase is the shared helper so the camera transport
	// (which has no explicit-override property of its own) derives the
	// identical fallback base.
	FString Sid = SessionId;
	if (Sid.IsEmpty())
	{
		Sid = ResolveActiveSessionBase(Mgr);
	}

	// Make the segment per-editor-process unique, matching the RPC transport's
	// scheme, so two render-server instances on one host don't both open the
	// process-global "live" (or same-labelled) state.shm. The camera transport
	// applies the identical transform to the same base so state.shm and
	// cam_*.shm stay co-located under one dir; that dir is advertised to the
	// client via AppendHandshakeBlock's shm_session_dir.
	Sid = MakeInstanceSessionId(Sid);

	const FString Dir = ResolveSessionDir(Sid);
	IFileManager::Get().MakeDirectory(*Dir, /*Tree=*/true);
	ResolvedPath = FPaths::Combine(Dir, TEXT("state.shm"));

	if (!StateRegion.Open(ResolvedPath, static_cast<uint32>(BufferStride), /*NBuffers=*/2))
	{
		UE_LOG(LogURLabNet, Error,
			TEXT("UURLabShmPublishTransport: failed to open SHM at %s"), *ResolvedPath);
		return false;
	}

	Mgr->RegisterSnapshotPublisher(this, this);

	UE_LOG(LogURLabNet, Log,
		TEXT("UURLabShmPublishTransport: writing state snapshots to %s"), *ResolvedPath);
	return true;
}

void UURLabShmPublishTransport::TransportShutdown()
{
	if (AAMjManager* Mgr = OwningManager.Get())
	{
		Mgr->UnregisterSnapshotPublisher(this);
	}
	// Manager tears the physics async thread down before calling
	// TransportShutdown, so no PostStep dispatch can race with this Close.
	StateRegion.Close(/*bDeleteFile=*/true);
}

void UURLabShmPublishTransport::Publish(const FString& /*Topic*/,
	const TArray<uint8>& Bytes)
{
	if (!StateRegion.IsOpen())
		return;

	FMjShmHeader* Hdr = static_cast<FMjShmHeader*>(StateRegion.GetData());
	if (!Hdr)
		return;

	const uint32 Stride = StateRegion.GetBufferStride();
	if (static_cast<uint32>(Bytes.Num()) + sizeof(uint32) > Stride)
	{
		UE_LOG(LogURLabNet, Warning,
			TEXT("UURLabShmPublishTransport: payload %d bytes exceeds slot stride %u; dropping"),
			Bytes.Num(), Stride);
		return;
	}

	// Write into the slot the consumer is *not* reading. The header's
	// latest_idx points at the last fully-published slot; we target the
	// next one in ring order, populate it, then atomically flip
	// latest_idx and bump the sequence counter.
	const uint32 CurrentLatest = Hdr->LatestIdx.load(std::memory_order_acquire);
	const uint32 NBuffers = Hdr->NBuffers > 0 ? Hdr->NBuffers : 1;
	const uint32 Target = (CurrentLatest + 1) % NBuffers;
	uint8* Slot = StateRegion.GetSlot(Target);
	if (!Slot)
		return;

	const uint32 PayloadSize = static_cast<uint32>(Bytes.Num());
	FMemory::Memcpy(Slot, &PayloadSize, sizeof(uint32));
	if (PayloadSize > 0)
	{
		FMemory::Memcpy(Slot + sizeof(uint32), Bytes.GetData(), PayloadSize);
	}

	Hdr->LatestIdx.store(Target, std::memory_order_release);
	Hdr->Sequence.fetch_add(1, std::memory_order_release);
}

void UURLabShmPublishTransport::AppendHandshakeBlock(TSharedPtr<FJsonObject>& Reply) const
{
	const FString ShmDir = FPaths::GetPath(GetStatePath());
	if (!ShmDir.IsEmpty())
	{
		Reply->SetStringField(TEXT("shm_session_dir"),
			FPaths::ConvertRelativePathToFull(ShmDir));
	}
}
