// Copyright (c) 2026 Jonathan Embley-Riches. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

#pragma once

// What a <texture> is once it is in Unreal: an asset, not a path.
//
// The same rule as <mesh>, and for the same reason: a `file="2_of_clubs.png"`
// left on the element is not something a user can edit, swap or validate, and
// every consumer that turned it back into a package path was guessing. The
// import pass produces a UTexture2D and this is where that asset is kept.
//
// A texture with no file is not a defect. `builtin="checker"` and friends are
// generated by MuJoCo's own compiler at load time, so the reference stays null
// and the preview keeps its flat colour.

#include "CoreMinimal.h"

#include "MuJoCo/Gen/Elements/Assets/MjTexture.gen.h"

#include "MjTexture.generated.h"

class UTexture2D;

/**
 * A `<texture>` element and the Unreal asset it stands for.
 *
 * The generated base owns every MJCF attribute; this owns the image that
 * element's `file` became.
 */
UCLASS(ClassGroup = (MuJoCo), meta = (BlueprintSpawnableComponent))
class URLAB_API UMjTexture : public UMjTextureBase
{
	GENERATED_BODY()

public:
	/**
	 * The image every material layer naming this texture samples.
	 *
	 * Set by the import pass to the asset it produced from `File`. Swapping it
	 * replaces the image: the next write dumps the new asset beside the model and
	 * points `File` at what it wrote.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "MuJoCo|Texture")
	TObjectPtr<UTexture2D> TextureAsset;

	/** The asset `File` stands for; see `UMjMesh::FileAsset`. */
	UPROPERTY()
	FSoftObjectPath FileAsset;

	/** True when `TextureAsset` is no longer the asset `File` stands for. */
	bool IsFileStale() const;

	/**
	 * Write `TextureAsset` out as a PNG under `BaseDirectory` and repoint `File`.
	 *
	 * Editor only: the pixels come from the texture's source data, which a cooked
	 * build does not carry. A cooked build cannot swap the asset either, so there
	 * is nothing there to reconcile.
	 */
	bool DumpAssetToFile(const FString& BaseDirectory);
};
