"""ProtoSpec Unreal emitter: schema AST -> the UE emission profile.

The third profile. It consumes the same AST :mod:`protospec_gen.frontend` builds
from upstream's ``src/xml/mjcf.schema`` and emits, into a URLab checkout, the
half of the UE spec model that scales with the schema:

    Public/MuJoCo/Gen/
      MjEnums.gen.h          one UENUM per schema enum, keywords as UMETA names
      MjKeywords.gen.h       enum <-> MJCF keyword declarations
      Elements/Mj<El>.gen.h  one UCLASS per schema element: UPROPERTYs + the
                             Get/Set/Has/Clear accessor quartet per attribute
      MjElements.gen.h       umbrella include + reference-target phantoms
      MjVisit.gen.h          the generated Visit hook the SDK and io consume
      MjStorage.gen.h        the Str and Shape policies over UE storage
      MjDefaults.gen.h       ApplyDefault declarations + the defaults prototype
      MjDispatch.gen.h       per-element dispatch: class <-> ElementType, child
                             storage slots, contextual XML tag recovery
      MjReflect.gen.h        per-element presence/clear thunks over TOptional
      MjProfile.gen.h        the generated half of the profile tag type
    Private/MuJoCo/Gen/
      MjKeywords.gen.cpp  MjDefaults.gen.cpp  MjDispatch.gen.cpp
      MjReflect.gen.cpp   MjCoverage.gen.cpp (generated schema-coverage test)

Storage mapping (plan Section 3.2):

===========================  ==========================================
schema                       UE
===========================  ==========================================
optional attribute           ``TOptional<T>`` UPROPERTY, EditAnywhere only
``required`` attribute       plain ``T``
``string`` / ``file``        ``FString``
``ref<ns>``                  ``FString`` slot, handed to Visit as ``RefView``
position ``double[3]``       ``FMjPosition3``
direction ``double[3]``      ``FMjDirection3``
every other ``double[3]``    ``FMjVec3`` (no conversion is ever right)
``double[2]``                ``FVector2D``
orientation ``double[4]``    ``FMjQuatRot`` (verbatim MJCF [w,x,y,z])
``float[4]``                 ``FLinearColor``
every other array            ``TArray<T>``
``enum`` / ``flags``         ``UENUM`` / ``TArray<UENUM>``
child lists                  nothing: the attachment hierarchy is the list
identity ``name``            ``UMjNodeComponent::MjName``
===========================  ==========================================

Hard emitter rules, none of which UHT catches:

* a ``TOptional`` UPROPERTY is ``EditAnywhere`` only -- never
  ``BlueprintReadWrite``/``BlueprintReadOnly`` (UHT accepts them and emits a
  ``bad_type`` Blueprint pin) and never ``Replicated`` (hard UHT error). The
  quartet is what Blueprint uses. Enforced by :func:`lint`.
* accessor-quartet parameters are plain inner types, never ``TOptional``, and
  carry no default values. Enforced by :func:`lint`.
* fixed-arity access is whole-array transfer through the ``Shape::fixed``
  adapter, never per-index: none of the frame types has an ``operator[]``, so
  an indexing assumption would compile for ``FVector`` and read a quaternion's
  components off by a slot. A quaternion default is written by named
  component for the same reason. Enforced by :func:`lint`.

The hand seams this output binds to, and nothing else: ``UMjNodeComponent``
(base class, public ``TOptional<FString> MjName``),
``urlab::RefView<Target, SlotType>`` (see MjVisit.gen.h's header comment for the
exact contract) and the frame types in ``MuJoCo/Spec/MjFrameTypes.h``:
``FMjQuatRot`` (four verbatim doubles named W, X, Y, Z, constructible in that
order) and ``FMjPosition3`` / ``FMjDirection3`` / ``FMjVec3`` (three verbatim
doubles named X, Y, Z, constructible in that order).

Entry point: ``python -m protospec_gen.emit_ue --out <URLab>`` writes the tree;
``--check`` regenerates in memory and fails on any byte difference. The URLab
root comes from ``--out``, else ``$PROTOSPEC_URLAB_ROOT``; with neither, the
profile is skipped with a stated reason so the fork's own gates still run.
"""

from __future__ import annotations

import argparse
import os
import re
import sys

from . import overlay
from .frontend import load_schema, pascal

# ASCII only, and lint() keeps the whole tree that way: MSVC decodes a source
# file without a BOM in the system codepage unless told otherwise, so a stray
# non-ASCII byte in a generated header is a warning on one machine and a build
# failure on another.
BANNER = "// Generated by protospec_gen.emit_ue -- do not edit."

# Every URLab source file carries this; generated files are no exception.
LICENSE = """\
// Copyright (c) 2026 Jonathan Embley-Riches. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
"""

ENV_ROOT = "PROTOSPEC_URLAB_ROOT"

PUBLIC = "Source/URLab/Public/MuJoCo/Gen"
PRIVATE = "Source/URLab/Private/MuJoCo/Gen"
# Automation tests live in the editor module, alongside the hand-written ones.
TESTS = "Source/URLabEditor/Private/Tests"


def element_family(s: "UeSchema", name: str) -> str:
    """The subfolder `name`'s generated header lands in, or "" for the root.

    `name` is the C++ element name; the overlay tables are keyed by the schema's
    own spelling, which is what a reader of `mjcf.schema` sees.

    Resolved from the schema's own sectioning -- an element belongs where the
    grammar declares it -- with `<default>` considered last, because it mirrors
    the whole grammar and would otherwise claim every element it partials.
    """
    elem = s.element_by_name.get(name)
    schema_name = elem["schema_name"] if elem else name
    override = overlay.UE_FAMILY_OF_ELEMENT.get(schema_name)
    if override is not None:
        return override

    index = getattr(s, "_family_index", None)
    if index is None:
        index = {}

        def children_of(cpp_name: str) -> list[str]:
            e = s.element_by_name.get(cpp_name)
            if e is None:
                return []
            out: list[str] = []
            for c in e["children"]:
                if c.get("union") is not None:
                    out.extend(s.union_by_name[c["union"]]["members"])
                else:
                    out.append(c["element"])
            return out

        def schema_of(cpp_name: str) -> str:
            e = s.element_by_name.get(cpp_name)
            return e["schema_name"] if e else cpp_name

        root = next((n for n, e in s.element_by_name.items()
                     if e["schema_name"] == "mujoco"), None)
        sections = children_of(root) if root else []
        # `default` last, so a section that really owns an element wins.
        sections = [x for x in sections if schema_of(x) != "default"] +                    [x for x in sections if schema_of(x) == "default"]
        for section in sections:
            family = overlay.UE_FAMILY_OF_SECTION.get(schema_of(section))
            if not family:
                continue
            seen: set[str] = set()
            queue = [section]
            while queue:
                cur = queue.pop(0)
                if cur in seen:
                    continue
                seen.add(cur)
                index.setdefault(cur, family)
                queue.extend(children_of(cur))
        s._family_index = index

    return index.get(name, "")

# Every reflected type the profile emits carries this prefix. It is URLab's
# ordinary one: a generated element IS the element, so <geom> is UMjGeom and
# <gyro> is UMjGyro, with nothing in the name to say who wrote the file. The
# directory, the .gen suffix and the banner already say that.
DEFAULT_PREFIX = "Mj"

# The elements URLab subclasses by hand, because they carry per-instance state
# the reflection system has to see: a render target and a worker thread on
# <camera>, visualizer mesh references on <geom>, a dynamic mesh on <flexcomp>,
# a pivot offset on <body>, and the imported UAsset a file-backed <mesh> or
# <texture> stands for.
#
# Only these have a naming problem, and only they pay for it. The hand class
# takes the canonical name and the generated class it derives from takes a
# "Base" suffix -- UMjGeom : UMjGeomBase. The suffix reads as what it is, and
# the base is left out of the Add Component picker below, because the thing a
# user places in a scene is always the hand class.
#
# <actuator> is deliberately absent: the control surface lives on the
# articulation, not on the element, so there is no hand subclass to name and the
# generated class is what a scene holds.
#
# This list is a naming policy and nothing more. The emitter does not know what
# the hand classes contain, does not declare them, and does not include them;
# a name that leaves this set simply loses its suffix on the next regeneration.
HAND_SUBCLASSED = frozenset({"Body", "Camera", "Flexcomp", "Geom", "Mesh", "Texture"})

HAND_BASE_SUFFIX = "Base"


class UeError(Exception):
    """A schema shape the UE profile cannot represent, or a name collision."""


# --------------------------------------------------------------------------- #
# Names                                                                        #
# --------------------------------------------------------------------------- #
# Identifiers a generated member or accessor may not take, because a UObject,
# UActorComponent or USceneComponent in the hierarchy already declares them.
# UHT reports a member clash, but a UFUNCTION clash with a virtual parent
# UFUNCTION of a different signature is the silent one, which is why the check
# is here rather than left to the build.
_RESERVED_MEMBERS = frozenset(
    """
    Class Name Outer World Owner Flags Package Archetype Mobility Bounds
    ComponentTags ComponentVelocity AttachParent AttachChildren AttachSocketName
    RelativeLocation RelativeRotation RelativeScale3D PrimaryComponentTick
    """.split()
)

# Accessor stems whose Get/Set/Has/Clear form would collide with a reflected
# function already declared in the component hierarchy. Scoped to UObject,
# UActorComponent and USceneComponent, which is what UMjNodeComponent derives
# from; UPrimitiveComponent's surface (SetMaterial and friends) is deliberately
# not listed, because a spec node is not a primitive.
_RESERVED_STEMS = frozenset(
    """
    Active Visibility Mobility Owner World Name Class Outer HiddenInGame
    IsReplicated ComponentTickEnabled RelativeLocation RelativeRotation
    RelativeScale3D WorldLocation WorldRotation
    """.split()
)

_CPP_KEYWORDS = frozenset(
    """
    alignas alignof and and_eq asm auto bitand bitor bool break case catch char
    class compl concept const consteval constexpr constinit const_cast continue
    decltype default delete do double dynamic_cast else enum explicit export
    extern false float for friend goto if inline int long mutable namespace new
    noexcept not not_eq nullptr operator or or_eq private protected public
    register reinterpret_cast requires return short signed sizeof static
    static_assert static_cast struct switch template this thread_local throw
    true try typedef typeid typename union unsigned using virtual void volatile
    wchar_t while xor xor_eq override final
    """.split()
)


def ident(name: str) -> str:
    return name + "_" if name in _CPP_KEYWORDS else name


def cpp_str(text: str) -> str:
    return (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )


def doc_comment(text: str, indent: str = "\t") -> list[str]:
    """A one-line doxygen comment, safe to sit inside a class body."""
    if not text:
        return []
    clean = text.replace("*/", "* /").replace("\n", " ").strip()
    return [f"{indent}/** {clean} */"]


# --------------------------------------------------------------------------- #
# Schema index                                                                 #
# --------------------------------------------------------------------------- #
class UeSchema:
    """The AST, indexed and named for the UE profile."""

    def __init__(self, doc: dict, prefix: str = DEFAULT_PREFIX):
        self.doc = doc
        self.prefix = prefix
        self.elements = doc["elements"]
        self.enums = doc["enums"]
        self.unions = doc["unions"]
        self.element_by_name = {e["name"]: e for e in self.elements}
        self.union_by_name = {u["name"]: u for u in self.unions}
        self.cls = {e["name"]: f"U{prefix}{self.type_stem(e['name'])}"
                    for e in self.elements}
        self.enum = {n["name"]: f"E{prefix}{n['name']}" for n in self.enums}
        self.union_tag = {u["name"]: f"F{prefix}{u['name']}" for u in self.unions}
        self._check_hand_bases()
        self._check_overlay()
        self._members: dict[tuple[str, str], str] = {}
        for e in self.elements:
            self._name_fields(e)

    # -- naming ------------------------------------------------------------- #
    @staticmethod
    def type_stem(name: str) -> str:
        """The element's reflected-type name after the prefix."""
        return name + HAND_BASE_SUFFIX if name in HAND_SUBCLASSED else name

    def is_hand_base(self, name: str) -> bool:
        """True when a hand subclass, not this class, is what a scene holds."""
        return name in HAND_SUBCLASSED

    def _check_hand_bases(self) -> None:
        """The suffix must name a class, and must not name someone else's."""
        for name in sorted(HAND_SUBCLASSED):
            if name not in self.element_by_name:
                raise UeError(
                    f"HAND_SUBCLASSED names {name!r}, which the schema does "
                    "not declare as an element")
        taken: dict[str, str] = {}
        for e in self.elements:
            cls = self.cls[e["name"]]
            if cls in taken:
                raise UeError(
                    f"{e['name']} and {taken[cls]} both map to the UE class "
                    f"{cls!r}")
            taken[cls] = e["name"]

    # -- overlay drift ------------------------------------------------------ #
    def _check_overlay(self) -> None:
        live = {f["xml"] for e in self.elements for f in e["fields"]}
        for attr in overlay.UE_MEMBER_NAMES:
            if attr not in live:
                raise UeError(
                    f"UE_MEMBER_NAMES renames {attr!r}, which the schema no "
                    "longer declares as an attribute")
        self._check_kinds()

    def _check_kinds(self) -> None:
        """UE_KIND covers exactly the schema's fixed double[3] and double[4]s.

        Exhaustive in both directions, which is what makes it self-retiring: a
        new spatial attribute has no kind and fails generation by name, and a
        kind for an attribute the schema retyped or dropped fails the same way.
        Without the first half a new `pos`-shaped attribute would quietly take
        whatever storage the fall-through gave it, which is the class of silent
        mistake the typed storage exists to remove.
        """
        shaped: dict[str, set[int]] = {}
        for e in self.elements:
            for f in e["fields"]:
                if _kind_shape(f) is not None:
                    shaped.setdefault(f["xml"], set()).add(
                        f["type"]["arity"]["size"])
        unclassified = sorted(a for a in shaped if a not in overlay.UE_KIND)
        if unclassified:
            raise UeError(
                "these attributes are a fixed double[3] or double[4] and have "
                "no overlay.UE_KIND entry, so the emitter cannot tell a point "
                "from a direction from a colour; classify each one:\n  " +
                "\n  ".join(unclassified))
        for attr, kind in sorted(overlay.UE_KIND.items()):
            if attr not in shaped:
                raise UeError(
                    f"UE_KIND classifies {attr!r} as {kind!r}, which the schema "
                    "no longer declares anywhere as a fixed double[3] or "
                    "double[4] attribute; delete the entry")
            for size in sorted(shaped[attr]):
                if kind in _KIND_UE and size not in _KIND_UE[kind]:
                    raise UeError(
                        f"UE_KIND classifies {attr!r} as {kind!r}, but the "
                        f"schema declares it as a double[{size}] and that kind "
                        f"only converts at {sorted(_KIND_UE[kind])} components")

    # -- member naming ------------------------------------------------------ #
    def _name_fields(self, elem: dict) -> None:
        seen: dict[str, str] = {}
        for f in elem["fields"]:
            if self.is_identity(f):
                continue
            member = overlay.UE_MEMBER_NAMES.get(f["xml"], pascal(f["name"]))
            if member in _RESERVED_MEMBERS or member in _RESERVED_STEMS:
                raise UeError(
                    f"{elem['name']}.{f['name']} maps to the UE member "
                    f"{member!r}, which the component hierarchy already "
                    "declares; add an overlay.UE_MEMBER_NAMES entry")
            if member in seen:
                raise UeError(
                    f"{elem['name']}.{f['name']} and {elem['name']}."
                    f"{seen[member]} both map to the UE member {member!r}")
            seen[member] = f["name"]
            self._members[(elem["name"], f["name"])] = member

    def member(self, elem: dict, f: dict) -> str:
        return self._members[(elem["name"], f["name"])]

    # -- field classification ----------------------------------------------- #
    @staticmethod
    def is_identity(f: dict) -> bool:
        """The element's own name attribute: stored on UMjNodeComponent."""
        return "namespace" in f.get("annotations", {})

    def has_identity(self, elem: dict) -> bool:
        return any(self.is_identity(f) for f in elem["fields"])

    def ref_target(self, f: dict) -> str:
        """The C++ phantom naming what a reference field may point at."""
        target = f["type"]["target"]
        if target in self.union_tag:
            return f"ps::ue::{self.union_tag[target]}"
        return self.cls[target]

    def stored_fields(self, elem: dict):
        """(field id, field) for every field with UE storage of its own."""
        return [(i, f) for i, f in enumerate(elem["fields"])
                if not self.is_identity(f)]


# --------------------------------------------------------------------------- #
# Type mapping                                                                 #
# --------------------------------------------------------------------------- #
_PRIM_UE = {
    "bool": "bool",
    "int32": "int32",
    "float": "float",
    "double": "double",
    "string": "FString",
}

# Fixed arities with a native UE vector type. Three- and four-double attributes
# are NOT here: their storage follows the overlay's kind classification below,
# because a point, a direction and a colour are the same shape and different
# types.
_FIXED_UE = {
    ("double", 2): "FVector2D",
    ("float", 4): "FLinearColor",
}

# The reflected type each kind stores in, per component count. A kind absent
# here converts to nothing and takes the raw storage: FMjVec3 at three
# components, a plain array at four.
_KIND_UE = {
    "position": {3: "FMjPosition3"},
    "direction": {3: "FMjDirection3"},
    # Same crossing rule as a direction (flip Y, leave the magnitude alone), so
    # the same type; overlay.UE_KIND keeps the two kinds distinct in the
    # classification even though the conversion cannot tell them apart.
    "physical": {3: "FMjDirection3"},
    "orientation": {4: "FMjQuatRot"},
}

# The kind-classified remainder at three components. Not FVector: an FVector in
# spec storage is exactly the confusion the kinds exist to remove, and this
# type says "three verbatim MJCF doubles, no frame, no conversion".
RAW_VEC3 = "FMjVec3"

# Every reflected type this profile stores a fixed-arity value in. `fixed<>`
# transfer is whole-array, so none of them may be indexed generically. FVector
# is deliberately absent: no attribute stores in it, because every double
# triple is kind-typed.
FIXED_TYPES = ("FVector2D", "FLinearColor", "FMjQuatRot",
               "FMjPosition3", "FMjDirection3", RAW_VEC3)

# The frame types the profile declares in MuJoCo/Spec/MjFrameTypes.h.
FRAME_TYPES = ("FMjQuatRot", "FMjPosition3", "FMjDirection3", RAW_VEC3)


def _kind_shape(f: dict) -> int | None:
    """The component count when a field is a fixed double[3] or double[4].

    The one place the gate's scope is stated, so the check and the storage
    decision cannot disagree about which attributes need a kind.
    """
    t = f["type"]
    if t.get("kind") != "prim" or t.get("prim") != "double":
        return None
    arity = t.get("arity")
    if arity is None or arity.get("kind") != "fixed":
        return None
    return arity["size"] if arity["size"] in (3, 4) else None


def value_type(s: UeSchema, f: dict) -> str:
    """The UE type of a field's value, before the presence wrapper."""
    t = f["type"]
    kind = t["kind"]
    if kind == "ref":
        return "FString"
    if kind == "named":
        name = s.enum[_enum_schema_name(s, t["name"])]
        return f"TArray<{name}>" if t.get("arity") is not None else name
    base = _PRIM_UE[t["prim"]]
    arity = t.get("arity")
    if arity is None:
        return base
    size = _kind_shape(f)
    if size is not None:
        # Checked exhaustive by UeSchema._check_kinds, so the lookup cannot miss.
        typed = _KIND_UE.get(overlay.UE_KIND[f["xml"]], {}).get(size)
        if typed is not None:
            return typed
        if size == 3:
            return RAW_VEC3
    elif arity["kind"] == "fixed":
        native = _FIXED_UE.get((t["prim"], arity["size"]))
        if native is not None:
            return native
    return f"TArray<{base}>"


def _enum_schema_name(s: UeSchema, ast_name: str) -> str:
    return ast_name


def stored_type(s: UeSchema, f: dict) -> str:
    """A field's UPROPERTY type: presence-wrapped unless the schema requires it."""
    vt = value_type(s, f)
    return f"TOptional<{vt}>" if f["optional"] else vt


def param_type(vt: str) -> str:
    """The accessor quartet's parameter type: the plain inner type, by const
    reference where a copy would be wasteful. Never TOptional, never defaulted."""
    if vt == "FString" or vt.startswith("TArray<"):
        return f"const {vt}&"
    return vt


# --------------------------------------------------------------------------- #
# Default values                                                               #
# --------------------------------------------------------------------------- #
def _num(value, prim: str) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if prim == "int32":
        return str(int(value))
    if prim == "float":
        return f"{float(value)}f"
    return f"{float(value)}"


def render_default(s: UeSchema, f: dict) -> str:
    """The schema `=` default as a UE expression.

    The quaternion case is the one the emitter must get right by hand: MJCF
    authors [w, x, y, z] and FQuat's constructor takes (X, Y, Z, W), so the
    default is permuted here by named component rather than positionally.
    """
    d = f["default"]
    t = f["type"]
    vt = value_type(s, f)
    if d["kind"] == "enum":
        return f"{vt}::{ident(d['member'])}"
    if d["kind"] == "scalar":
        if t["kind"] == "prim" and t["prim"] == "string":
            return f'FString(TEXT("{cpp_str(str(d["value"]))}"))'
        if t["kind"] == "ref":
            return f'FString(TEXT("{cpp_str(str(d["value"]))}"))'
        return _num(d["value"], t.get("prim", "double"))
    values = d["values"]
    prim = t["prim"]
    if vt == "FVector2D":
        x, y = (_num(v, prim) for v in values)
        return f"FVector2D({x}, {y})"
    if vt == "FLinearColor":
        r, g, b, a = (_num(v, prim) for v in values)
        return f"FLinearColor({r}, {g}, {b}, {a})"
    if vt in ("FMjPosition3", "FMjDirection3", RAW_VEC3):
        x, y, z = (_num(v, prim) for v in values)
        return f"{vt}({x}, {y}, {z})"
    if vt == "FMjQuatRot":
        w, x, y, z = (_num(v, prim) for v in values)
        return f"FMjQuatRot(/*W=*/{w}, /*X=*/{x}, /*Y=*/{y}, /*Z=*/{z})"
    inner = _PRIM_UE[prim] if t["kind"] == "prim" else vt[len("TArray<"):-1]
    joined = ", ".join(_num(v, prim) for v in values)
    return f"TArray<{inner}>({{{joined}}})"


def zero_value(vt: str) -> str:
    """What Get() falls back to for a field the schema gives no default."""
    if vt == "FVector2D":
        return "FVector2D::ZeroVector"
    if vt in FRAME_TYPES:
        return f"{vt}()"
    if vt == "FLinearColor":
        return "FLinearColor(0.0f, 0.0f, 0.0f, 0.0f)"
    if vt == "bool":
        return "false"
    if vt in ("int32", "float", "double"):
        return "0" if vt == "int32" else ("0.0f" if vt == "float" else "0.0")
    if vt == "FString":
        return "FString()"
    if vt.startswith("TArray<"):
        return f"{vt}()"
    return f"static_cast<{vt}>(0)"  # enum: the schema's first keyword


def get_fallback(s: UeSchema, f: dict) -> str:
    return render_default(s, f) if "default" in f else zero_value(value_type(s, f))


# --------------------------------------------------------------------------- #
# Elements                                                                     #
# --------------------------------------------------------------------------- #
def element_header(s: UeSchema, elem: dict) -> str:
    o: list[str] = []
    w = o.append
    name = elem["name"]
    cls = s.cls[name]
    w(LICENSE.rstrip("\n"))
    w("")
    w(BANNER)
    w("//")
    w(f"// <{elem['xml']}>: {len(elem['fields'])} schema attributes, of which "
      f"{len(s.stored_fields(elem))} carry storage here")
    w("// (the identity attribute lives on UMjNodeComponent::MjName).")
    w("#pragma once")
    w("")
    w('#include "CoreMinimal.h"')
    w('#include "MuJoCo/Spec/MjNodeComponent.h"')
    if _uses_frame_type(s, elem):
        w('#include "MuJoCo/Spec/MjFrameTypes.h"')
    if _uses_enum(s, elem):
        w('#include "MuJoCo/Gen/MjEnums.gen.h"')
    w("")
    w(f'#include "Mj{name}.gen.generated.h"')
    w("")
    if elem.get("alias"):
        w(f"// The schema aliases <{elem['xml']}> onto <{elem['alias']}>, so it")
        w("// admits that element's children.")
    if s.is_hand_base(name):
        # URLab subclasses this element by hand, and the subclass is what a
        # scene holds, so it -- not this -- is the one the picker offers.
        w(f"// URLab derives UMj{name} from this and places that; the schema")
        w("// attributes are here and the hand behaviour is there.")
        w("UCLASS(ClassGroup = (MuJoCo))")
    else:
        w("UCLASS(ClassGroup = (MuJoCo), meta = (BlueprintSpawnableComponent))")
    w(f"class URLAB_API {cls} : public UMjNodeComponent")
    w("{")
    w("\tGENERATED_BODY()")
    w("")
    w("public:")

    category = name
    for fid, f in s.stored_fields(elem):
        vt = value_type(s, f)
        st = stored_type(s, f)
        member = s.member(elem, f)
        for line in doc_comment(_field_doc(f), "\t"):
            w(line)
        meta = [f'ToolTip = "{cpp_str(_field_doc(f))}"']
        if f["type"]["kind"] == "ref":
            meta.append(f'GetOptions = "Get{member}Options"')
        spec = f'EditAnywhere, Category = "{_ue_category(category, f)}"'
        if f["xml"] in overlay.UE_ADVANCED:
            spec += ", AdvancedDisplay"
        spec += f", meta = ({', '.join(meta)})"
        w(f"\tUPROPERTY({spec})")
        w(f"\t{st} {member};")
        w("")

    w("\t// --- Blueprint access ---")
    w("\t// TOptional has no Blueprint pin, so presence and value reach")
    w("\t// Blueprint through this quartet. Get() falls back to the schema")
    w("\t// default; it does NOT resolve the default-class chain, which is")
    w("\t// EffectiveField's job.")
    for fid, f in s.stored_fields(elem):
        vt = value_type(s, f)
        member = s.member(elem, f)
        pt = param_type(vt)
        cat = f"MuJoCo|{category}"
        w(f'\tUFUNCTION(BlueprintPure, Category = "{cat}")')
        if f["optional"]:
            w(f"\tbool Has{member}() const {{ return {member}.IsSet(); }}")
        else:
            w(f"\tbool Has{member}() const {{ return true; }}")
        w("")
        w(f'\tUFUNCTION(BlueprintPure, Category = "{cat}")')
        if f["optional"]:
            w(f"\t{vt} Get{member}() const "
              f"{{ return {member}.Get({get_fallback(s, f)}); }}")
        else:
            w(f"\t{vt} Get{member}() const {{ return {member}; }}")
        w("")
        w(f'\tUFUNCTION(BlueprintCallable, Category = "{cat}")')
        w(f"\tvoid Set{member}({pt} InValue) {{ {member} = InValue; }}")
        w("")
        if f["optional"]:
            w(f'\tUFUNCTION(BlueprintCallable, Category = "{cat}")')
            w(f"\tvoid Clear{member}() {{ {member}.Reset(); }}")
            w("")
        if f["type"]["kind"] == "ref":
            w("\tUFUNCTION()")
            w(f"\tTArray<FString> Get{member}Options() const")
            w(f"\t{{ return RefNameOptions({fid}); }}")
            w("")
    w("};")
    return "\n".join(o) + "\n"


def _field_doc(f: dict) -> str:
    doc = f.get("doc", "")
    return f"{doc} (MJCF: {f['xml']})" if doc else f"MJCF: {f['xml']}"


def _ue_category(element: str, f: dict) -> str:
    """The details-panel category an attribute is filed under.

    Everything the schema generates sits under one `MuJoCo` root, so an
    element's own attributes and the ones `UMjNodeComponent` contributes read as
    one panel rather than as two unrelated top-level groups.

    Below that, the element names the group and the schema's `use` groups name
    the sub-groups: an actuator's transmission attributes are the schema's own
    statement that those seven belong together, so the panel says so too. An
    attribute the element declared inline has no such statement behind it and
    stays at the element's own level, which is most of them -- a geom's are all
    inline, and inventing sub-groups for it would be this file's opinion rather
    than the schema's.
    """
    base = f"MuJoCo|{element}"
    group = f.get("group")
    return f"{base}|{pascal(group)}" if group else base


def _uses_enum(s: UeSchema, elem: dict) -> bool:
    return any(f["type"]["kind"] == "named" for _i, f in s.stored_fields(elem))


def _uses_frame_type(s: UeSchema, elem: dict) -> bool:
    return any(value_type(s, f) in FRAME_TYPES for _i, f in s.stored_fields(elem))


def emit_elements_umbrella(s: UeSchema) -> str:
    o: list[str] = []
    w = o.append
    w(LICENSE.rstrip("\n"))
    w("")
    w(BANNER)
    w("//")
    w("// Every generated element class, plus the phantom target types a")
    w("// reference to a shared MuJoCo namespace points at (a `joint` reference")
    w("// names <joint> or <freejoint>, so its target is the namespace, not one")
    w("// class). The phantoms are never instantiated; the element types each")
    w("// admits are in MjDispatch.gen.h, which is where ElementType arrives.")
    w("//")
    w("// Engine-only by construction: this file and everything it includes are")
    w("// the UHT-visible surface, and none of it names ProtoSpec.")
    w("#pragma once")
    w("")
    w('#include "CoreMinimal.h"')
    for e in s.elements:
        fam = element_family(s, e["name"])
        sub = f"{fam}/" if fam else ""
        w(f'#include "MuJoCo/Gen/Elements/{sub}Mj{e["name"]}.gen.h"')
    w("")
    w("namespace ps::ue")
    w("{")
    for u in s.unions:
        w(f"struct {s.union_tag[u['name']]} {{}};")
    w("")
    w("}  // namespace ps::ue")
    return "\n".join(o) + "\n"


# --------------------------------------------------------------------------- #
# Enums and keywords                                                           #
# --------------------------------------------------------------------------- #
def emit_enums(s: UeSchema) -> str:
    o: list[str] = []
    w = o.append
    w(LICENSE.rstrip("\n"))
    w("")
    w(BANNER)
    w("//")
    w("// One UENUM per schema enum. Enumerator ORDER is the contract: a value")
    w("// crosses the profile seam as its schema declaration index, which is")
    w("// also the MJCF keyword order, so these must stay in step with")
    w("// ps::mjcf's plain enums. The MJCF keyword is the display name.")
    w("#pragma once")
    w("")
    w('#include "CoreMinimal.h"')
    w("")
    w('#include "MjEnums.gen.generated.h"')
    for e in s.enums:
        w("")
        for line in doc_comment(e.get("doc", ""), ""):
            w(line)
        w("UENUM(BlueprintType)")
        w(f"enum class {s.enum[e['name']]} : uint8")
        w("{")
        for m in e["members"]:
            w(f'\t{ident(m["name"])} UMETA(DisplayName = "{cpp_str(m["value"])}"),')
        w("};")
    return "\n".join(o) + "\n"


def emit_keywords_h(s: UeSchema) -> str:
    o: list[str] = []
    w = o.append
    w(LICENSE.rstrip("\n"))
    w("")
    w(BANNER)
    w("//")
    w("// Enum <-> MJCF keyword tables for the UE enums. Separate from the plain")
    w("// profile's because the enum types differ; the keyword strings and their")
    w("// order do not.")
    w("#pragma once")
    w("")
    w("#include <string_view>")
    w("")
    w('#include "CoreMinimal.h"')
    w("")
    w('#include "MuJoCo/Gen/MjEnums.gen.h"')
    w("")
    w("namespace ps::ue")
    w("{")
    for e in s.enums:
        name = s.enum[e["name"]]
        w(f"URLAB_API std::string_view ToMjcf({name} Value);")
        w(f"URLAB_API bool FromMjcf(std::string_view Text, {name}& Out);")
    w("")
    w("}  // namespace ps::ue")
    return "\n".join(o) + "\n"


def emit_keywords_cpp(s: UeSchema) -> str:
    o: list[str] = []
    w = o.append
    w(LICENSE.rstrip("\n"))
    w("")
    w(BANNER)
    w("")
    w('#include "MuJoCo/Gen/MjKeywords.gen.h"')
    w("")
    w("namespace ps::ue")
    w("{")
    for e in s.enums:
        name = s.enum[e["name"]]
        w("")
        w(f"std::string_view ToMjcf({name} Value)")
        w("{")
        w("\tswitch (Value)")
        w("\t{")
        for m in e["members"]:
            w(f'\tcase {name}::{ident(m["name"])}: return "{cpp_str(m["value"])}";')
        w("\tdefault: return \"\";")
        w("\t}")
        w("}")
        w("")
        w(f"bool FromMjcf(std::string_view Text, {name}& Out)")
        w("{")
        for m in e["members"]:
            w(f'\tif (Text == "{cpp_str(m["value"])}") {{ Out = {name}::'
              f"{ident(m['name'])}; return true; }}")
        w("\treturn false;")
        w("}")
    w("")
    w("}  // namespace ps::ue")
    return "\n".join(o) + "\n"


# --------------------------------------------------------------------------- #
# Visit                                                                        #
# --------------------------------------------------------------------------- #
def emit_visit(s: UeSchema) -> str:
    o: list[str] = []
    w = o.append
    w(LICENSE.rstrip("\n"))
    w("")
    w(BANNER)
    w("//")
    w("// The generated Visit hook: one traversal, N consumers. V receives every")
    w("// attribute by schema field id + MJCF name + typed reference. Field ids")
    w("// are the SCHEMA's, shared with every other profile and with the reflect")
    w("// and xml_binding tables, so a table-driven reader and writer need no")
    w("// knowledge of UE storage.")
    w("//")
    w("// No child calls: the attachment hierarchy is the child list, so children")
    w("// reach the SDK through the tree adapter (MjDispatch.gen.h supplies the")
    w("// per-element storage slots it needs) rather than through Visit.")
    w("//")
    w("// A reference field is handed over wrapped, because its storage -- a")
    w("// name string -- is indistinguishable from a plain string attribute and")
    w("// the reference scan must be able to tell them apart at compile time.")
    w("// The wrapper is the one hand seam this file needs:")
    w("//")
    w("//   template <class Target, class SlotType = TOptional<FString>>")
    w("//   struct RefView            // urlab, MuJoCo/Spec/MjRefView.h")
    w("//   {")
    w("//     SlotType& Slot;                       // aggregate-initialized")
    w("//     using TargetType = Target;            // phantom, as ps::Ref<T>")
    w("//     bool IsSet() const;                   // set AND non-empty")
    w("//     FStringView Get() const;")
    w("//     void Set(FStringView Name) const;     // empty name clears")
    w("//     void Clear() const;")
    w("//     SlotType* SlotPtr() const { return &Slot; }")
    w("//   };")
    w("//")
    w("// SlotType is spelled explicitly at every call below, because a required")
    w("// reference stores a plain FString and the const traversal binds a const")
    w("// slot; Set/Clear must be constrained out when SlotType is const.")
    w("// SlotPtr matters: the view itself is a temporary that dies with the")
    w("// Visit frame, so a Ref policy handing out a RefSlot must build its ops")
    w("// over the storage the view points at, never over the view.")
    w("#pragma once")
    w("")
    w('#include <utility>')
    w("")
    w('#include "MuJoCo/Spec/MjRefView.h"')
    w('#include "MuJoCo/Gen/MjElements.gen.h"')
    w("")
    w("namespace ps::ue")
    w("{")
    for e in s.elements:
        for const in (False, True):
            _visit_one(s, e, const, w)
    w("}  // namespace ps::ue")
    return "\n".join(o) + "\n"


def _visit_one(s: UeSchema, elem: dict, const: bool, w) -> None:
    cls = s.cls[elem["name"]]
    qual = "const " if const else ""
    w("")
    w("template <class V>")
    w(f"void Visit({qual}{cls}& Element, V&& Vis)")
    w("{")
    body = False
    for fid, f in enumerate(elem["fields"]):
        xml = f["xml"]
        if UeSchema.is_identity(f):
            w(f'\tVis.field({fid}, "{xml}", Element.MjName);')
            body = True
            continue
        member = s.member(elem, f)
        if f["type"]["kind"] == "ref":
            slot = "FString" if not f["optional"] else "TOptional<FString>"
            if const:
                slot = f"const {slot}"
            target = s.ref_target(f)
            w(f"\turlab::RefView<{target}, {slot}> Ref{fid}{{ Element.{member} }};")
            w(f'\tVis.field({fid}, "{xml}", Ref{fid});')
        else:
            w(f'\tVis.field({fid}, "{xml}", Element.{member});')
        body = True
    if not body:
        w("\t(void)Element;")
    w("\t(void)Vis;")
    w("}")


# --------------------------------------------------------------------------- #
# Storage policies (Str, Shape)                                                #
# --------------------------------------------------------------------------- #
def emit_storage(s: UeSchema) -> str:
    """The Str and Shape policies. Derived from the storage decisions this
    emitter makes, so they ship with it rather than being restated by hand."""
    o: list[str] = []
    w = o.append
    w(LICENSE.rstrip("\n"))
    w("")
    w(BANNER)
    w("//")
    w("// The UE profile's string and attribute-storage policies.")
    w("//")
    w("// Shape is what lets the profile-generic reader and writer read and write")
    w("// UE storage without naming any of it. The load-bearing part is the fixed")
    w("// adapter: transfer is WHOLE-ARRAY in MJCF component order, never indexed,")
    w("// because FMjQuatRot has no operator[]. Code that indexed a fixed value")
    w("// generically would compile for FVector and read a quaternion off by a slot.")
    w("//")
    w("// A range-arity attribute and an unbounded one share TArray storage, so")
    w("// their bounds cannot be recovered from the type. The reader enforces them")
    w("// from the binding table's arity instead (mjcf_reader.inc, ReadVector).")
    w("#pragma once")
    w("")
    w("#include <cstddef>")
    w("#include <string>")
    w("#include <string_view>")
    w("#include <type_traits>")
    w("#include <utility>")
    w("")
    w('#include "CoreMinimal.h"')
    w('#include "Containers/StringConv.h"')
    w('#include "Containers/StringView.h"')
    w("")
    w('#include "MuJoCo/Spec/MjFrameTypes.h"')
    w('#include "MuJoCo/Spec/MjRefView.h"')
    w('#include "MuJoCo/Gen/MjKeywords.gen.h"')
    w('#include "protospec/profile.h"')
    w("")
    w("namespace ps::ue")
    w("{")
    w("namespace sdk = ps::sdk;")
    w("")
    w("// --- Str ---------------------------------------------------------- //")
    w("struct FMjStrPolicy")
    w("{")
    w("\tusing string = FString;")
    w("\tusing view = FStringView;")
    w("")
    w("\tstatic view View(const string& S) { return view(S); }")
    w("")
    w("\tstatic string FromUtf8(std::string_view U)")
    w("\t{")
    w("\t\tFUTF8ToTCHAR Conv(U.data(), static_cast<int32>(U.size()));")
    w("\t\treturn FString::ConstructFromPtrSize(Conv.Get(), Conv.Length());")
    w("\t}")
    w("")
    w("\tstatic std::string ToUtf8(view V)")
    w("\t{")
    w("\t\tFTCHARToUTF8 Conv(V.GetData(), V.Len());")
    w("\t\treturn std::string(Conv.Get(), static_cast<std::size_t>(Conv.Length()));")
    w("\t}")
    w("")
    w("\tstatic bool Equals(view A, view B)")
    w("\t{ return A.Equals(B, ESearchCase::CaseSensitive); }")
    w("")
    w("\tstatic bool EqualsUtf8(view A, std::string_view B)")
    w("\t{ return ToUtf8(A) == B; }")
    w("")
    w("\tstatic bool Empty(view V) { return V.IsEmpty(); }")
    w("")
    w("\tstatic bool StartsWith(view V, std::string_view P)")
    w("\t{")
    w("\t\tconst string Pattern = FromUtf8(P);")
    w("\t\treturn V.StartsWith(view(Pattern), ESearchCase::CaseSensitive);")
    w("\t}")
    w("")
    w("\tstatic string Concat(view A, view B) { return string(A) + string(B); }")
    w("")
    w("\t// Case-insensitive, as every FString hash in the engine is. Equal keys")
    w("\t// still hash equal, which is all a name index needs.")
    w("\tstatic std::size_t Hash(view V)")
    w("\t{ return static_cast<std::size_t>(GetTypeHash(V)); }")
    w("};")
    w("")
    w("// --- Shape -------------------------------------------------------- //")
    w("// The value a reference slot reads as: a name, distinguishable at compile")
    w("// time from a plain string attribute, and default-constructible so the")
    w("// reader can build one before authoring it.")
    w("struct FMjRefName")
    w("{")
    w("\tFString Name;")
    w("};")
    w("")
    w("namespace storage")
    w("{")
    w("template <class T> struct TIsOptional : std::false_type { using Inner = T; };")
    w("template <class T> struct TIsOptional<TOptional<T>> : std::true_type")
    w("{ using Inner = T; };")
    w("")
    w("// The reference-view trait is RefView's own (MjRefView.h) rather than a")
    w("// second copy: a trait kept in step by hand with a type it does not own")
    w("// is a drift source, and this one would fail silently, by classifying")
    w("// every reference as a plain string attribute.")
    w("using urlab::ref_view_detail::TIsRefView;")
    w("")
    w("template <class T> struct TIsArray : std::false_type {};")
    w("template <class T> struct TIsArray<TArray<T>> : std::true_type")
    w("{ using Element = T; };")
    w("")
    w("template <class T> struct TInnerOf { using Type = T; };")
    w("template <class T> struct TInnerOf<TOptional<T>> { using Type = T; };")
    w("template <class A, class B> struct TInnerOf<urlab::RefView<A, B>>")
    w("{ using Type = FMjRefName; };")
    w("")
    w("template <class I>")
    w("constexpr sdk::Shape KindOf()")
    w("{")
    w("\tif constexpr (std::is_same_v<I, FMjRefName>) { return sdk::Shape::Ref; }")
    w("\telse if constexpr (std::is_same_v<I, FString>) { return sdk::Shape::Str; }")
    w("\telse if constexpr (std::is_same_v<I, bool>) { return sdk::Shape::Bool; }")
    w("\telse if constexpr (std::is_enum_v<I>) { return sdk::Shape::Enum; }")
    w("\telse if constexpr (")
    for i, t in enumerate(FIXED_TYPES):
        tail = ")" if i == len(FIXED_TYPES) - 1 else " ||"
        w(f"\t\tstd::is_same_v<I, {t}>{tail}")
    w("\t{ return sdk::Shape::Fixed; }")
    w("\telse if constexpr (TIsArray<I>::value)")
    w("\t{")
    w("\t\tif constexpr (std::is_enum_v<typename TIsArray<I>::Element>)")
    w("\t\t\treturn sdk::Shape::EnumList;")
    w("\t\telse")
    w("\t\t\treturn sdk::Shape::Unbounded;")
    w("\t}")
    w("\telse if constexpr (std::is_arithmetic_v<I>) { return sdk::Shape::Scalar; }")
    w("\telse { return sdk::Shape::Unknown; }")
    w("}")
    w("}  // namespace storage")
    w("")
    w("struct FMjShape")
    w("{")
    w("\ttemplate <class T>")
    w("\tstatic constexpr bool optional_v =")
    w("\t\tstorage::TIsOptional<std::decay_t<T>>::value ||")
    w("\t\tstorage::TIsRefView<std::decay_t<T>>::value;")
    w("")
    w("\ttemplate <class T>")
    w("\tusing inner_t = typename storage::TInnerOf<std::decay_t<T>>::Type;")
    w("")
    w("\ttemplate <class T>")
    w("\tstatic bool IsSet(const T& Slot)")
    w("\t{")
    w("\t\tif constexpr (storage::TIsRefView<std::decay_t<T>>::value)")
    w("\t\t\treturn Slot.IsSet();")
    w("\t\telse if constexpr (storage::TIsOptional<std::decay_t<T>>::value)")
    w("\t\t\treturn Slot.IsSet();")
    w("\t\telse")
    w("\t\t\treturn true;")
    w("\t}")
    w("")
    w("\t// A reference slot has no stored FMjRefName to hand back, so this")
    w("\t// returns by value there; callers bind the result to a const reference,")
    w("\t// which extends its lifetime.")
    w("\ttemplate <class T>")
    w("\tstatic decltype(auto) Read(const T& Slot)")
    w("\t{")
    w("\t\tif constexpr (storage::TIsRefView<std::decay_t<T>>::value)")
    w("\t\t\treturn FMjRefName{ FString(Slot.Get()) };")
    w("\t\telse if constexpr (storage::TIsOptional<std::decay_t<T>>::value)")
    w("\t\t\treturn (Slot.GetValue());")
    w("\t\telse")
    w("\t\t\treturn (Slot);")
    w("\t}")
    w("")
    w("\ttemplate <class T>")
    w("\tstatic void Author(T& Slot, inner_t<T> Value)")
    w("\t{")
    w("\t\tif constexpr (storage::TIsRefView<std::decay_t<T>>::value)")
    w("\t\t\tSlot.Set(FStringView(Value.Name));")
    w("\t\telse")
    w("\t\t\tSlot = MoveTemp(Value);")
    w("\t}")
    w("")
    w("\ttemplate <class T>")
    w("\tstatic void Reset(T& Slot)")
    w("\t{")
    w("\t\tif constexpr (storage::TIsRefView<std::decay_t<T>>::value)")
    w("\t\t\tSlot.Clear();")
    w("\t\telse if constexpr (storage::TIsOptional<std::decay_t<T>>::value)")
    w("\t\t\tSlot.Reset();")
    w("\t}")
    w("")
    w("\ttemplate <class I>")
    w("\tstatic constexpr sdk::Shape kind_v = storage::KindOf<std::decay_t<I>>();")
    w("")
    w("\t// UTF-8 by value: an FString is UTF-16, so there is no borrowable")
    w("\t// std::string_view over it. io holds the result rather than a view into")
    w("\t// it (mjcf_writer.inc FormatValue).")
    w("\ttemplate <class I>")
    w("\tstatic std::string StrGet(const I& V)")
    w("\t{ return FMjStrPolicy::ToUtf8(FStringView(V)); }")
    w("")
    w("\ttemplate <class I>")
    w("\tstatic I StrMake(std::string_view V) { return FMjStrPolicy::FromUtf8(V); }")
    w("")
    w("\ttemplate <class I>")
    w("\tstatic std::string RefGet(const I& V)")
    w("\t{ return FMjStrPolicy::ToUtf8(FStringView(V.Name)); }")
    w("")
    w("\ttemplate <class I>")
    w("\tstatic I RefMake(std::string_view V)")
    w("\t{ return I{ FMjStrPolicy::FromUtf8(V) }; }")
    w("")
    w("\ttemplate <class I>")
    w("\tstatic I EnumMake(int Index) { return static_cast<I>(Index); }")
    w("")
    w("\ttemplate <class I>")
    w("\tstatic int EnumIndex(const I& V) { return static_cast<int>(V); }")
    w("")
    w("\ttemplate <class I>")
    w("\tstatic bool EnumFromMjcf(std::string_view Keyword, I& Out)")
    w("\t{ return ps::ue::FromMjcf(Keyword, Out); }")
    w("")
    w("\ttemplate <class I>")
    w("\tstatic std::string_view EnumToMjcf(const I& V)")
    w("\t{ return ps::ue::ToMjcf(V); }")
    w("")
    w("\ttemplate <class I> struct fixed;")
    w("\ttemplate <class I> struct seq;")
    w("\ttemplate <class I> struct reflist;")
    w("};")
    w("")
    w("template <>")
    w("struct FMjShape::fixed<FVector2D>")
    w("{")
    w("\tusing scalar = double;")
    w("\tstatic constexpr std::size_t size = 2;")
    w("\tstatic void Load(const FVector2D& V, double* Out)")
    w("\t{ Out[0] = V.X; Out[1] = V.Y; }")
    w("\tstatic FVector2D Make(const double* In)")
    w("\t{ return FVector2D(In[0], In[1]); }")
    w("};")
    w("")
    w("// The kind-typed triples are stored exactly as MJCF authors them, in")
    w("// MuJoCo's frame and MuJoCo's units, so each of these is a straight copy.")
    w("// Nothing in the spec layer flips an axis or rescales a length: the")
    w("// types' own ToUnreal is the sole route into Unreal space, and FMjVec3")
    w("// deliberately has none.")
    for vec in ("FMjPosition3", "FMjDirection3", "FMjVec3"):
        w("template <>")
        w(f"struct FMjShape::fixed<{vec}>")
        w("{")
        w("\tusing scalar = double;")
        w("\tstatic constexpr std::size_t size = 3;")
        w(f"\tstatic void Load(const {vec}& V, double* Out)")
        w("\t{ Out[0] = V.X; Out[1] = V.Y; Out[2] = V.Z; }")
        w(f"\tstatic {vec} Make(const double* In)")
        w(f"\t{{ return {vec}(In[0], In[1], In[2]); }}")
        w("};")
        w("")
    w("// A quaternion is stored exactly as MJCF authors it, [w, x, y, z], so this")
    w("// is a straight copy too. FMjQuatRot::ToUnreal is the only route to an")
    w("// Unreal rotation.")
    w("template <>")
    w("struct FMjShape::fixed<FMjQuatRot>")
    w("{")
    w("\tusing scalar = double;")
    w("\tstatic constexpr std::size_t size = 4;")
    w("\tstatic void Load(const FMjQuatRot& V, double* Out)")
    w("\t{ Out[0] = V.W; Out[1] = V.X; Out[2] = V.Y; Out[3] = V.Z; }")
    w("\tstatic FMjQuatRot Make(const double* In)")
    w("\t{ return FMjQuatRot(In[0], In[1], In[2], In[3]); }")
    w("};")
    w("")
    w("template <>")
    w("struct FMjShape::fixed<FLinearColor>")
    w("{")
    w("\tusing scalar = float;")
    w("\tstatic constexpr std::size_t size = 4;")
    w("\tstatic void Load(const FLinearColor& V, float* Out)")
    w("\t{ Out[0] = V.R; Out[1] = V.G; Out[2] = V.B; Out[3] = V.A; }")
    w("\tstatic FLinearColor Make(const float* In)")
    w("\t{ return FLinearColor(In[0], In[1], In[2], In[3]); }")
    w("};")
    w("")
    w("template <class S>")
    w("struct FMjShape::seq<TArray<S>>")
    w("{")
    w("\tusing scalar = S;")
    w("\tstatic constexpr std::size_t max_size = 0;  // 0 == unbounded")
    w("\tstatic std::size_t Size(const TArray<S>& V)")
    w("\t{ return static_cast<std::size_t>(V.Num()); }")
    w("\tstatic void Load(const TArray<S>& V, S* Out)")
    w("\t{ for (int32 I = 0; I < V.Num(); ++I) Out[I] = V[I]; }")
    w("\tstatic TArray<S> Make(const S* In, std::size_t N)")
    w("\t{")
    w("\t\tTArray<S> Out;")
    w("\t\tOut.Reserve(static_cast<int32>(N));")
    w("\t\tfor (std::size_t I = 0; I < N; ++I) Out.Add(In[I]);")
    w("\t\treturn Out;")
    w("\t}")
    w("};")
    w("")
    w("}  // namespace ps::ue")
    return "\n".join(o) + "\n"


# --------------------------------------------------------------------------- #
# Defaults                                                                     #
# --------------------------------------------------------------------------- #
def emit_defaults_h(s: UeSchema) -> str:
    o: list[str] = []
    w = o.append
    w(LICENSE.rstrip("\n"))
    w("")
    w(BANNER)
    w("//")
    w("// The schema's `=` defaults. Never stamped onto a spec node: an")
    w("// authored spec carries exactly what was authored, and an unset")
    w("// attribute is what makes default-class inheritance fire at compile.")
    w("// These exist for the two readers of a default: the generated Get()")
    w("// accessors (inlined per field) and the class-chain resolution in")
    w("// classes.h, which asks for a prototype through SchemaDefaults.")
    w("#pragma once")
    w("")
    w('#include "UObject/Package.h"')
    w('#include "UObject/UObjectGlobals.h"')
    w("")
    w('#include "MuJoCo/Gen/MjElements.gen.h"')
    w("")
    w("namespace ps::ue")
    w("{")
    for e in s.elements:
        w(f"void ApplyDefault({s.cls[e['name']]}& Element);")
    w("")
    w("// A shared, immutable instance carrying only the schema defaults: the")
    w("// lowest-priority layer of the class merge, without a NewObject per")
    w("// query. Game thread only, and never handed out mutably.")
    w("template <class T>")
    w("const T& SchemaDefaults()")
    w("{")
    w("\tstatic T* Prototype = nullptr;")
    w("\tif (Prototype == nullptr)")
    w("\t{")
    w("\t\tPrototype = NewObject<T>(GetTransientPackage(), NAME_None, RF_Transient);")
    w("\t\tPrototype->AddToRoot();")
    w("\t\tApplyDefault(*Prototype);")
    w("\t}")
    w("\treturn *Prototype;")
    w("}")
    w("")
    w("}  // namespace ps::ue")
    return "\n".join(o) + "\n"


def emit_defaults_cpp(s: UeSchema) -> str:
    o: list[str] = []
    w = o.append
    w(LICENSE.rstrip("\n"))
    w("")
    w(BANNER)
    w("")
    w('#include "MuJoCo/Gen/MjDefaults.gen.h"')
    w("")
    w("namespace ps::ue")
    w("{")
    for e in s.elements:
        w("")
        w(f"void ApplyDefault({s.cls[e['name']]}& Element)")
        w("{")
        any_default = False
        for _fid, f in s.stored_fields(e):
            if "default" in f:
                any_default = True
                w(f"\tElement.{s.member(e, f)} = {render_default(s, f)};")
        if not any_default:
            w("\t(void)Element;")
        w("}")
    w("")
    w("}  // namespace ps::ue")
    return "\n".join(o) + "\n"


# --------------------------------------------------------------------------- #
# Dispatch                                                                     #
# --------------------------------------------------------------------------- #
def child_slots(s: UeSchema, elem: dict) -> list[tuple[int, str, str]]:
    """(storage slot, child element name, contextual XML tag) for every element
    type this element admits as a child.

    The slot is the schema child index, which is what the writer indexes to
    recover a contextual tag (<worldbody> for a body under the model, <joint>
    for a composite's joint) and what the reader groups its child pass by.
    """
    out: list[tuple[int, str, str]] = []
    for slot, c in enumerate(elem["children"]):
        if c.get("union") is not None:
            for m in s.union_by_name[c["union"]]["members"]:
                out.append((slot, m, s.element_by_name[m]["xml"]))
        else:
            out.append((slot, c["element"], c["tag"]))
    return out


def emit_dispatch_h(s: UeSchema) -> str:
    o: list[str] = []
    w = o.append
    w(LICENSE.rstrip("\n"))
    w("")
    w(BANNER)
    w("//")
    w("// Per-element dispatch: everything a tree adapter, a node factory or a")
    w("// details customization needs to get from a runtime element identity to a")
    w("// concrete generated class, and back. All of it scales with the schema, so")
    w("// none of it is a hand-written switch.")
    w("//")
    w("// ChildSlots is the contract the tree adapters implement ForEachChildSlot")
    w("// against: it enumerates, per element type, the storage slots it admits")
    w("// and the concrete class each slot accepts. The slot number is the schema")
    w("// child index, so the writer recovers the contextual tag from the shared")
    w("// binding table and the reader groups its child pass by it.")
    w("#pragma once")
    w("")
    w("#include <type_traits>")
    w("#include <utility>")
    w("")
    w('#include "CoreMinimal.h"')
    w('#include "Components/SceneComponent.h"')
    w("")
    w('#include "MuJoCo/Gen/MjElements.gen.h"')
    w('#include "protospec/profile.h"')
    w("")
    w("namespace ps::ue")
    w("{")
    w("using ps::mjcf::ElementType;")
    w("")
    w("// --- Schema identity of a generated class ------------------------- //")
    w("template <class E> struct TMjElementType;")
    w("template <ElementType E> struct TMjElementOf;")
    w("")
    for e in s.elements:
        cls = s.cls[e["name"]]
        w(f"template <> struct TMjElementType<{cls}>")
        w(f"{{ static constexpr ElementType Value = ElementType::{e['name']}; }};")
    w("")
    for e in s.elements:
        cls = s.cls[e["name"]]
        w(f"template <> struct TMjElementOf<ElementType::{e['name']}>")
        w(f"{{ using Type = {cls}; }};")
    w("")
    w("// The element types a reference field may name: one for a concrete")
    w("// target, every declarer of the namespace for a shared one. The typed")
    w("// half of what detail::RefTargetsAt answers at runtime.")
    w("template <class Target> struct TMjRefTargets;")
    w("")
    for e in s.elements:
        w(f"template <> struct TMjRefTargets<{s.cls[e['name']]}>")
        w(f"{{ static constexpr ElementType Types[] = "
          f"{{ ElementType::{e['name']} }}; }};")
    for u in s.unions:
        members = ", ".join(f"ElementType::{m}" for m in u["members"])
        w(f"template <> struct TMjRefTargets<{s.union_tag[u['name']]}>")
        w(f"{{ static constexpr ElementType Types[] = {{ {members} }}; }};")
    w("")
    w("// True when the schema gives the element an identity attribute, so its")
    w("// MjName is authored data rather than an always-empty slot.")
    w("template <class E> struct TMjHasName : std::false_type {};")
    for e in s.elements:
        if s.has_identity(e):
            w(f"template <> struct TMjHasName<{s.cls[e['name']]}> : std::true_type {{}};")
    w("")
    w("// --- Runtime tables ------------------------------------------------ //")
    w("/** The generated class an element type names, or null. */")
    w("UClass* ClassForElement(ElementType Type);")
    w("")
    w("/** The element type a class (or the nearest generated base of a")
    w(" *  presentation subclass) names. False when it is not a spec node. */")
    w("bool ElementTypeOfClass(const UClass* Class, ElementType& Out);")
    w("")
    w("/** As above, for a live node. */")
    w("bool ElementTypeOfNode(const UMjNodeComponent& Node, ElementType& Out);")
    w("")
    w("/** The element's own MJCF tag (what it is called at the top level). */")
    w("const TCHAR* TagForElement(ElementType Type);")
    w("")
    w("/** The element a top-level MJCF tag names. */")
    w("bool ElementTypeForTag(FStringView Tag, ElementType& Out);")
    w("")
    w("/** The element a tag names IN CONTEXT, which is not always the same: the")
    w(" *  schema routes <worldbody> to a body and <joint> under <composite> to a")
    w(" *  composite joint. Reports the storage slot the child would occupy. */")
    w("bool ElementTypeForChildTag(ElementType Parent, FStringView Tag,")
    w("\tElementType& OutChild, int32& OutSlot);")
    w("")
    w("/** The tag a child of this type is WRITTEN as under this parent. */")
    w("const TCHAR* ChildTagFor(ElementType Parent, ElementType Child);")
    w("")
    w("/** The storage slot a child of this type occupies under this parent, or")
    w(" *  -1 when the parent does not admit it. */")
    w("int32 SlotFor(ElementType Parent, ElementType Child);")
    w("")
    w("/** Every (slot, admissible child type) pair a parent admits. */")
    w("void ForEachAdmissibleChild(ElementType Parent,")
    w("\tTFunctionRef<void(int32 Slot, ElementType Child)> Fn);")
    w("")
    w("/** Names of every element in the spec that a reference field could")
    w(" *  legally point at: the backing of every generated GetOptions dropdown. */")
    w("TArray<FString> RefNameOptions(const UMjNodeComponent* Node, int32 FieldId);")
    w("")
    w("// --- Compile-time dispatch ----------------------------------------- //")
    w("// The storage slots an element admits, as (slot, TypeTag<Class>). The")
    w("// overload set is the schema's; a tree adapter forwards to it.")
    for e in s.elements:
        slots = child_slots(s, e)
        w("")
        w("template <class Fn>")
        w(f"void ChildSlots(const {s.cls[e['name']]}*, Fn&& Callback)")
        w("{")
        if not slots:
            w("\t(void)Callback;")
        for slot, child, _tag in slots:
            w(f"\tCallback({slot}, ps::sdk::TypeTag<{s.cls[child]}>{{}});")
        w("}")
    w("")
    w("// Recover a node's concrete generated type. The 144-way switch is the")
    w("// profile's business, not an algorithm's.")
    w("template <class Fn>")
    w("bool DispatchByType(UMjNodeComponent& Node, Fn&& Callback)")
    w("{")
    w("\tElementType Type;")
    w("\tif (!ElementTypeOfNode(Node, Type)) return false;")
    w("\tswitch (Type)")
    w("\t{")
    for e in s.elements:
        cls = s.cls[e["name"]]
        w(f"\tcase ElementType::{e['name']}:")
        w(f"\t\tCallback(static_cast<{cls}&>(Node)); return true;")
    w("\tdefault: return false;")
    w("\t}")
    w("}")
    w("")
    w("template <class Fn>")
    w("bool DispatchByType(const UMjNodeComponent& Node, Fn&& Callback)")
    w("{")
    w("\treturn DispatchByType(const_cast<UMjNodeComponent&>(Node),")
    w("\t\t[&](auto& Element)")
    w("\t\t{ Callback(static_cast<const std::decay_t<decltype(Element)>&>(Element)); });")
    w("}")
    w("")
    w("}  // namespace ps::ue")
    return "\n".join(o) + "\n"


def emit_dispatch_cpp(s: UeSchema) -> str:
    o: list[str] = []
    w = o.append
    w(LICENSE.rstrip("\n"))
    w("")
    w(BANNER)
    w("")
    w('#include "MuJoCo/Gen/MjDispatch.gen.h"')
    w("")
    w("#include <vector>")
    w("")
    w('#include "protospec/detail.h"')
    w("")
    w("namespace ps::ue")
    w("{")
    w("namespace")
    w("{")
    w("struct FElementRow")
    w("{")
    w("\tElementType Type;")
    w("\tUClass* (*StaticClassFn)();")
    w("\tconst TCHAR* Tag;")
    w("};")
    w("")
    w("const FElementRow* ElementRows(int32& OutCount)")
    w("{")
    w("\tstatic const FElementRow Rows[] = {")
    for e in s.elements:
        cls = s.cls[e["name"]]
        w(f'\t\t{{ ElementType::{e["name"]}, &{cls}::StaticClass, '
          f'TEXT("{cpp_str(e["xml"])}") }},')
    w("\t};")
    w("\tOutCount = UE_ARRAY_COUNT(Rows);")
    w("\treturn Rows;")
    w("}")
    w("")
    w("struct FChildRow")
    w("{")
    w("\tElementType Parent;")
    w("\tint32 Slot;")
    w("\tElementType Child;")
    w("\tconst TCHAR* Tag;")
    w("};")
    w("")
    w("// One row per (parent, storage slot, admissible child type). The tag is")
    w("// the CONTEXTUAL one: what the schema calls that child under that parent.")
    w("const FChildRow* ChildRows(int32& OutCount)")
    w("{")
    w("\tstatic const FChildRow Rows[] = {")
    total = 0
    for e in s.elements:
        for slot, child, tag in child_slots(s, e):
            total += 1
            w(f'\t\t{{ ElementType::{e["name"]}, {slot}, ElementType::{child}, '
              f'TEXT("{cpp_str(tag)}") }},')
    if total == 0:
        w("\t\t{},")
    w("\t};")
    w("\tOutCount = UE_ARRAY_COUNT(Rows);")
    w("\treturn Rows;")
    w("}")
    w("")
    w("void CollectNames(const USceneComponent* Node,")
    w("\tconst std::vector<ElementType>& Targets, TArray<FString>& Out)")
    w("{")
    w("\tif (Node == nullptr) return;")
    w("\tif (const UMjNodeComponent* Doc = Cast<UMjNodeComponent>(Node))")
    w("\t{")
    w("\t\tElementType Type;")
    w("\t\tif (Doc->MjName.IsSet() && ElementTypeOfNode(*Doc, Type))")
    w("\t\t{")
    w("\t\t\tfor (ElementType Want : Targets)")
    w("\t\t\t{")
    w("\t\t\t\tif (Want == Type) { Out.AddUnique(Doc->MjName.GetValue()); break; }")
    w("\t\t\t}")
    w("\t\t}")
    w("\t}")
    w("\tfor (const USceneComponent* Child : Node->GetAttachChildren())")
    w("\t\tCollectNames(Child, Targets, Out);")
    w("}")
    w("")
    w("}  // namespace")
    w("")
    w("UClass* ClassForElement(ElementType Type)")
    w("{")
    w("\tint32 Count = 0;")
    w("\tconst FElementRow* Rows = ElementRows(Count);")
    w("\tfor (int32 I = 0; I < Count; ++I)")
    w("\t\tif (Rows[I].Type == Type) return Rows[I].StaticClassFn();")
    w("\treturn nullptr;")
    w("}")
    w("")
    w("bool ElementTypeOfClass(const UClass* Class, ElementType& Out)")
    w("{")
    w("\tint32 Count = 0;")
    w("\tconst FElementRow* Rows = ElementRows(Count);")
    w("\t// A presentation subclass (UMjBox over a geom) is the element its")
    w("\t// nearest generated base names, so walk up rather than matching exactly.")
    w("\tfor (const UClass* C = Class; C != nullptr; C = C->GetSuperClass())")
    w("\t\tfor (int32 I = 0; I < Count; ++I)")
    w("\t\t\tif (Rows[I].StaticClassFn() == C) { Out = Rows[I].Type; return true; }")
    w("\treturn false;")
    w("}")
    w("")
    w("bool ElementTypeOfNode(const UMjNodeComponent& Node, ElementType& Out)")
    w("{")
    w("\treturn ElementTypeOfClass(Node.GetClass(), Out);")
    w("}")
    w("")
    w("const TCHAR* TagForElement(ElementType Type)")
    w("{")
    w("\tint32 Count = 0;")
    w("\tconst FElementRow* Rows = ElementRows(Count);")
    w("\tfor (int32 I = 0; I < Count; ++I)")
    w("\t\tif (Rows[I].Type == Type) return Rows[I].Tag;")
    w("\treturn TEXT(\"\");")
    w("}")
    w("")
    w("bool ElementTypeForTag(FStringView Tag, ElementType& Out)")
    w("{")
    w("\tint32 Count = 0;")
    w("\tconst FElementRow* Rows = ElementRows(Count);")
    w("\tfor (int32 I = 0; I < Count; ++I)")
    w("\t{")
    w("\t\tif (Tag.Equals(FStringView(Rows[I].Tag), ESearchCase::CaseSensitive))")
    w("\t\t{ Out = Rows[I].Type; return true; }")
    w("\t}")
    w("\treturn false;")
    w("}")
    w("")
    w("bool ElementTypeForChildTag(ElementType Parent, FStringView Tag,")
    w("\tElementType& OutChild, int32& OutSlot)")
    w("{")
    w("\tint32 Count = 0;")
    w("\tconst FChildRow* Rows = ChildRows(Count);")
    w("\tfor (int32 I = 0; I < Count; ++I)")
    w("\t{")
    w("\t\tif (Rows[I].Parent != Parent) continue;")
    w("\t\tif (!Tag.Equals(FStringView(Rows[I].Tag), ESearchCase::CaseSensitive))")
    w("\t\t\tcontinue;")
    w("\t\tOutChild = Rows[I].Child;")
    w("\t\tOutSlot = Rows[I].Slot;")
    w("\t\treturn true;")
    w("\t}")
    w("\treturn false;")
    w("}")
    w("")
    w("const TCHAR* ChildTagFor(ElementType Parent, ElementType Child)")
    w("{")
    w("\tint32 Count = 0;")
    w("\tconst FChildRow* Rows = ChildRows(Count);")
    w("\tfor (int32 I = 0; I < Count; ++I)")
    w("\t\tif (Rows[I].Parent == Parent && Rows[I].Child == Child)")
    w("\t\t\treturn Rows[I].Tag;")
    w("\treturn TagForElement(Child);")
    w("}")
    w("")
    w("int32 SlotFor(ElementType Parent, ElementType Child)")
    w("{")
    w("\tint32 Count = 0;")
    w("\tconst FChildRow* Rows = ChildRows(Count);")
    w("\tfor (int32 I = 0; I < Count; ++I)")
    w("\t\tif (Rows[I].Parent == Parent && Rows[I].Child == Child)")
    w("\t\t\treturn Rows[I].Slot;")
    w("\treturn -1;")
    w("}")
    w("")
    w("void ForEachAdmissibleChild(ElementType Parent,")
    w("\tTFunctionRef<void(int32 Slot, ElementType Child)> Fn)")
    w("{")
    w("\tint32 Count = 0;")
    w("\tconst FChildRow* Rows = ChildRows(Count);")
    w("\tfor (int32 I = 0; I < Count; ++I)")
    w("\t\tif (Rows[I].Parent == Parent) Fn(Rows[I].Slot, Rows[I].Child);")
    w("}")
    w("")
    w("TArray<FString> RefNameOptions(const UMjNodeComponent* Node, int32 FieldId)")
    w("{")
    w("\tTArray<FString> Out;")
    w("\tif (Node == nullptr) return Out;")
    w("\tElementType Self;")
    w("\tif (!ElementTypeOfNode(*Node, Self)) return Out;")
    w("\tconst std::vector<ElementType> Targets =")
    w("\t\tps::sdk::detail::RefTargetsAt(Self, FieldId);")
    w("\tif (Targets.empty()) return Out;")
    w("\tconst USceneComponent* Root = Node;")
    w("\twhile (Root->GetAttachParent() != nullptr) Root = Root->GetAttachParent();")
    w("\tCollectNames(Root, Targets, Out);")
    w("\tOut.Sort();")
    w("\treturn Out;")
    w("}")
    w("")
    w("}  // namespace ps::ue")
    return "\n".join(o) + "\n"


# --------------------------------------------------------------------------- #
# Reflect thunks                                                               #
# --------------------------------------------------------------------------- #
def emit_reflect_h(s: UeSchema) -> str:
    o: list[str] = []
    w = o.append
    w(LICENSE.rstrip("\n"))
    w("")
    w(BANNER)
    w("//")
    w("// The per-profile half of reflection: presence and clear over this")
    w("// profile's storage, keyed by the schema's element type and field id.")
    w("//")
    w("// Everything else an ElementDescriptor carries -- names, XML spellings,")
    w("// kinds, arities, defaults, constraints -- is schema identity and is")
    w("// already emitted once into ps::mjcf::reflect, which URLab links. Only the")
    w("// thunks vary by profile, so only the thunks are emitted here; the")
    w("// descriptor's own present/clear members belong to the plain profile and")
    w("// must not be called on a UE node.")
    w("#pragma once")
    w("")
    w('#include "MuJoCo/Gen/MjElements.gen.h"')
    w('#include "reflect.h"')
    w("")
    w("namespace ps::ue")
    w("{")
    w("using ps::mjcf::ElementType;")
    w("")
    w("struct FMjElementThunks")
    w("{")
    w("\tbool (*Present)(const void* Element, int FieldId);")
    w("\tvoid (*Clear)(void* Element, int FieldId);")
    w("};")
    w("")
    w("/** The thunks for an element type. Always valid: an unknown type gets a")
    w(" *  pair that reports absence and clears nothing. */")
    w("const FMjElementThunks& Thunks(ElementType Type);")
    w("")
    w("/** The shared schema descriptor, for callers that want both halves. */")
    w("const ps::mjcf::reflect::ElementDescriptor& Describe(ElementType Type);")
    w("")
    w("}  // namespace ps::ue")
    return "\n".join(o) + "\n"


def emit_reflect_cpp(s: UeSchema) -> str:
    o: list[str] = []
    w = o.append
    w(LICENSE.rstrip("\n"))
    w("")
    w(BANNER)
    w("")
    w('#include "MuJoCo/Gen/MjReflect.gen.h"')
    w("")
    w("namespace ps::ue")
    w("{")
    w("namespace")
    w("{")
    for e in s.elements:
        cls = s.cls[e["name"]]
        name = e["name"]
        w("")
        w(f"bool Present_{name}(const void* P, int FieldId)")
        w("{")
        if not e["fields"]:
            w("\t(void)P; (void)FieldId;")
            w("\treturn false;")
        else:
            w(f"\tconst {cls}& E = *static_cast<const {cls}*>(P);")
            w("\t(void)E;")
            w("\tswitch (FieldId)")
            w("\t{")
            for fid, f in enumerate(e["fields"]):
                if UeSchema.is_identity(f):
                    w(f"\tcase {fid}: return E.MjName.IsSet();")
                elif f["optional"]:
                    w(f"\tcase {fid}: return E.{s.member(e, f)}.IsSet();")
                else:
                    w(f"\tcase {fid}: return true;")
            w("\tdefault: return false;")
            w("\t}")
        w("}")
        w("")
        clearable = [(fid, f) for fid, f in enumerate(e["fields"])
                     if f["optional"]]
        w(f"void Clear_{name}(void* P, int FieldId)")
        w("{")
        if not clearable:
            w("\t(void)P; (void)FieldId;")
        else:
            w(f"\t{cls}& E = *static_cast<{cls}*>(P);")
            w("\tswitch (FieldId)")
            w("\t{")
            for fid, f in clearable:
                if UeSchema.is_identity(f):
                    w(f"\tcase {fid}: E.MjName.Reset(); break;")
                else:
                    w(f"\tcase {fid}: E.{s.member(e, f)}.Reset(); break;")
            w("\tdefault: break;")
            w("\t}")
        w("}")
    w("")
    w("bool Present_None(const void*, int) { return false; }")
    w("void Clear_None(void*, int) {}")
    w("")
    w("struct FThunkRow")
    w("{")
    w("\tElementType Type;")
    w("\tFMjElementThunks Thunks;")
    w("};")
    w("")
    w("const FThunkRow Rows[] = {")
    for e in s.elements:
        name = e["name"]
        w(f"\t{{ ElementType::{name}, {{ &Present_{name}, &Clear_{name} }} }},")
    w("};")
    w("")
    w("const FMjElementThunks NoThunks{ &Present_None, &Clear_None };")
    w("")
    w("}  // namespace")
    w("")
    w("const FMjElementThunks& Thunks(ElementType Type)")
    w("{")
    w("\tfor (const FThunkRow& Row : Rows)")
    w("\t\tif (Row.Type == Type) return Row.Thunks;")
    w("\treturn NoThunks;")
    w("}")
    w("")
    w("const ps::mjcf::reflect::ElementDescriptor& Describe(ElementType Type)")
    w("{")
    w("\treturn ps::mjcf::reflect::Describe(Type);")
    w("}")
    w("")
    w("}  // namespace ps::ue")
    return "\n".join(o) + "\n"


# --------------------------------------------------------------------------- #
# Profile                                                                      #
# --------------------------------------------------------------------------- #
def emit_profile(s: UeSchema) -> str:
    o: list[str] = []
    w = o.append
    w(LICENSE.rstrip("\n"))
    w("")
    w(BANNER)
    w("//")
    w("// The generated half of the UE emission profile: every policy and")
    w("// primitive that follows from the schema. The four that follow from UE")
    w("// instead -- what the spec root is, how children are stored, how a")
    w("// reference slot is proxied, how identity and duplication work -- are hand")
    w("// seams, and a complete profile is this base plus those four:")
    w("//")
    w("//   struct FMjUeProfile : ps::ue::FMjGeneratedProfile")
    w("//   {")
    w("//     using Doc   = FMjSpecPolicy;     // FSpecRef, MuJoCo/Spec/MjSpecRef.h")
    w("//     using Tree  = FMjTreeAdapter;   // MuJoCo/Spec/MjTreeAdapters.h")
    w("//     using Ref   = FMjRefPolicy;     // over urlab::RefView")
    w("//     using Ident = FMjIdentPolicy;   // Serial, SourceFile/Line, clone")
    w("//   };")
    w("//")
    w("// Tree::ForEachChildSlot forwards to ps::ue::ChildSlots (MjDispatch.gen.h)")
    w("// and Tree::ForEachChildAt reports the slot ps::ue::SlotFor gives, which is")
    w("// what makes the writer's contextual tag lookup work.")
    w("#pragma once")
    w("")
    w("#include <optional>")
    w("#include <type_traits>")
    w("#include <utility>")
    w("")
    w('#include "MuJoCo/Gen/MjDefaults.gen.h"')
    w('#include "MuJoCo/Gen/MjDispatch.gen.h"')
    w('#include "MuJoCo/Gen/MjStorage.gen.h"')
    w('#include "MuJoCo/Gen/MjVisit.gen.h"')
    w("")
    w("namespace ps::ue")
    w("{")
    w("struct FMjGeneratedProfile")
    w("{")
    w("\tusing Str = FMjStrPolicy;")
    w("\tusing Shape = FMjShape;")
    w("")
    w("\ttemplate <class E, class V>")
    w("\tstatic void Visit(E& Element, V&& Vis)")
    w("\t{ ps::ue::Visit(Element, std::forward<V>(Vis)); }")
    w("")
    w("\ttemplate <class E>")
    w("\tstatic constexpr ps::mjcf::ElementType type_of =")
    w("\t\tTMjElementType<std::decay_t<E>>::Value;")
    w("")
    w("\ttemplate <ps::mjcf::ElementType E>")
    w("\tusing element_t = typename TMjElementOf<E>::Type;")
    w("")
    w("\t// The schema's answer, not the storage's: every node has an MjName slot,")
    w("\t// but only an element the schema gives an identity attribute can be")
    w("\t// named, referenced or renamed.")
    w("\ttemplate <class E>")
    w("\tstatic constexpr bool has_name = TMjHasName<std::decay_t<E>>::value;")
    w("")
    w("\ttemplate <class E>")
    w("\tstatic std::optional<FStringView> Name(const E& Element)")
    w("\t{")
    w("\t\tif (!Element.MjName.IsSet()) return std::nullopt;")
    w("\t\treturn FStringView(Element.MjName.GetValue());")
    w("\t}")
    w("")
    w("\ttemplate <class E>")
    w("\tstatic void SetName(E& Element, FStringView NewName)")
    w("\t{ Element.MjName = FString(NewName); }")
    w("")
    w("\ttemplate <class E>")
    w("\tstatic void ApplyDefault(E& Element) { ps::ue::ApplyDefault(Element); }")
    w("")
    w("\ttemplate <class E>")
    w("\tstatic const E& Defaults() { return ps::ue::SchemaDefaults<E>(); }")
    w("};")
    w("")
    w("// The schema-identity map is total and injective, checked here rather than")
    w("// by a test, so a regeneration that lost an element cannot link.")
    for e in s.elements:
        cls = s.cls[e["name"]]
        w(f"static_assert(TMjElementType<{cls}>::Value == "
          f"ps::mjcf::ElementType::{e['name']});")
        w(f"static_assert(std::is_same_v<TMjElementOf<"
          f"ps::mjcf::ElementType::{e['name']}>::Type, {cls}>);")
    w("")
    w("}  // namespace ps::ue")
    return "\n".join(o) + "\n"


# --------------------------------------------------------------------------- #
# Generated coverage test                                                      #
# --------------------------------------------------------------------------- #
def emit_coverage(s: UeSchema) -> str:
    """The schema-coverage assertion, generated from the schema rather than
    written by hand: every element has a registered UCLASS, every attribute a
    registered FProperty of the expected storage, every enum a UENUM whose
    enumerator order matches the schema.

    One function per element and per enum, rather than one body over the whole
    schema: a schema this size makes a single function tens of thousands of
    instructions long, which MSVC reports as C4883 (function size suppresses
    optimizations) and UE promotes to an error. The split also puts the failing
    element's name in the stack frame."""
    o: list[str] = []
    w = o.append
    w(LICENSE.rstrip("\n"))
    w("")
    w(BANNER)
    w("//")
    w("// Schema coverage, asserted against UE's own reflection rather than")
    w("// against the emitter's intent: a property that failed to register (a")
    w("// storage type UHT silently dropped, a specifier that produced a bad_type)")
    w("// is invisible at compile time and fails here.")
    w("")
    w('#include "CoreMinimal.h"')
    w('#include "Misc/AutomationTest.h"')
    w("")
    w('#include "MuJoCo/Spec/MjGenHooks.h"')
    w("")
    w("#if URLAB_MJ_GEN && WITH_DEV_AUTOMATION_TESTS")
    w("")
    w('#include "UObject/UnrealType.h"')
    w("")
    w('#include "MuJoCo/Gen/MjElements.gen.h"')
    w('#include "MuJoCo/Gen/MjEnums.gen.h"')
    w("")
    w("IMPLEMENT_SIMPLE_AUTOMATION_TEST(FMjGenSchemaCoverageTest,")
    w('\t"URLab.Gen.SchemaCoverage",')
    w("\tEAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)")
    w("")
    w("namespace")
    w("{")
    w("bool HasProperty(FAutomationTestBase& Test, UClass* Class,")
    w("\tconst TCHAR* PropertyName)")
    w("{")
    w("\tconst FProperty* Property = Class->FindPropertyByName(FName(PropertyName));")
    w("\tif (Property == nullptr)")
    w("\t{")
    w("\t\tTest.AddError(FString::Printf(TEXT(\"%s has no property %s\"),")
    w("\t\t\t*Class->GetName(), PropertyName));")
    w("\t\treturn false;")
    w("\t}")
    w("\treturn true;")
    w("}")
    w("")
    w("bool HasFunction(FAutomationTestBase& Test, UClass* Class,")
    w("\tconst TCHAR* FunctionName)")
    w("{")
    w("\tif (Class->FindFunctionByName(FName(FunctionName)) == nullptr)")
    w("\t{")
    w("\t\tTest.AddError(FString::Printf(TEXT(\"%s has no function %s\"),")
    w("\t\t\t*Class->GetName(), FunctionName));")
    w("\t\treturn false;")
    w("\t}")
    w("\treturn true;")
    w("}")
    for e in s.elements:
        cls = s.cls[e["name"]]
        w("")
        w(f"// <{e['xml']}>")
        w(f"void CoverElement{e['name']}(FAutomationTestBase& Test)")
        w("{")
        w(f"\tUClass* const Class = {cls}::StaticClass();")
        w(f'\tTest.TestNotNull(TEXT("{cls} is registered"), Class);')
        for _fid, f in s.stored_fields(e):
            member = s.member(e, f)
            w(f'\tHasProperty(Test, Class, TEXT("{member}"));')
            w(f'\tHasFunction(Test, Class, TEXT("Get{member}"));')
            w(f'\tHasFunction(Test, Class, TEXT("Set{member}"));')
            w(f'\tHasFunction(Test, Class, TEXT("Has{member}"));')
            if f["optional"]:
                w(f'\tHasFunction(Test, Class, TEXT("Clear{member}"));')
        w("}")
    for en in s.enums:
        name = s.enum[en["name"]]
        w("")
        w(f"void CoverEnum{en['name']}(FAutomationTestBase& Test)")
        w("{")
        w(f"\tUEnum* const Enum = StaticEnum<{name}>();")
        w(f'\tTest.TestNotNull(TEXT("{name} is registered"), Enum);')
        w("\tif (Enum == nullptr)")
        w("\t{")
        w("\t\treturn;")
        w("\t}")
        w(f'\tTest.TestEqual(TEXT("{name} keyword count"),')
        w(f"\t\tEnum->NumEnums() - 1, {len(en['members'])});")
        for i, m in enumerate(en["members"]):
            w(f'\tTest.TestEqual(TEXT("{name}[{i}] keyword"),')
            w(f"\t\tEnum->GetDisplayNameTextByIndex({i}).ToString(),")
            w(f'\t\tFString(TEXT("{cpp_str(m["value"])}")));')
        w("}")
    w("}  // namespace")
    w("")
    w("bool FMjGenSchemaCoverageTest::RunTest(const FString& Parameters)")
    w("{")
    for e in s.elements:
        w(f"\tCoverElement{e['name']}(*this);")
    w("")
    for en in s.enums:
        w(f"\tCoverEnum{en['name']}(*this);")
    w("")
    w("\treturn !HasAnyErrors();")
    w("}")
    w("")
    w("#endif  // URLAB_MJ_GEN && WITH_DEV_AUTOMATION_TESTS")
    return "\n".join(o) + "\n"


# --------------------------------------------------------------------------- #
# Regeneration scripts                                                         #
# --------------------------------------------------------------------------- #
def emit_regen_ps1() -> str:
    return """\
# Generated by protospec_gen.emit_ue -- do not edit.
#
# Regenerate URLab's MuJoCo spec profile from the MJCF schema.
#
# The generator lives in the plugin (protospec/), and reads the schema from the
# MuJoCo submodule: a MuJoCo bump moves the grammar and this regenerates against
# it, without a ProtoSpec change dragging MuJoCo's own build along with it.
#
#   .\\Scripts\\regen_ue_profile.ps1            # rewrite Source/URLab/*/MuJoCo/Gen
#   .\\Scripts\\regen_ue_profile.ps1 -Check     # fail if it is out of date
[CmdletBinding()]
param(
    [switch]$Check,
    [string]$ProtospecRoot
)
$ErrorActionPreference = "Stop"

$UrlabRoot = Split-Path -Parent $PSScriptRoot
if (-not $ProtospecRoot) {
    $ProtospecRoot = Join-Path $UrlabRoot "protospec"
}
if (-not (Test-Path (Join-Path $ProtospecRoot "protospec_gen"))) {
    throw "No ProtoSpec generator at $ProtospecRoot. Pass -ProtospecRoot."
}

$Args = @("run", "python", "-m", "protospec_gen.emit_ue", "--out", $UrlabRoot)
if ($Check) { $Args += "--check" }

Push-Location $ProtospecRoot
try {
    & uv @Args
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
}
finally {
    Pop-Location
}
"""


def emit_regen_sh() -> str:
    return """\
#!/usr/bin/env bash
# Generated by protospec_gen.emit_ue -- do not edit.
#
# Regenerate URLab's MuJoCo spec profile from the MJCF schema.
#
# The generator lives in the plugin (protospec/), and reads the schema from the
# MuJoCo submodule: a MuJoCo bump moves the grammar and this regenerates against
# it, without a ProtoSpec change dragging MuJoCo's own build along with it.
#
#   ./Scripts/regen_ue_profile.sh          # rewrite Source/URLab/*/MuJoCo/Gen
#   ./Scripts/regen_ue_profile.sh --check  # fail if it is out of date
set -euo pipefail

check=""
protospec_root=""
while [ $# -gt 0 ]; do
    case "$1" in
        --check) check="--check"; shift ;;
        --protospec-root) protospec_root="$2"; shift 2 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
urlab_root="$(dirname "$script_dir")"
if [ -z "$protospec_root" ]; then
    protospec_root="$urlab_root/protospec"
fi
if [ ! -d "$protospec_root/protospec_gen" ]; then
    echo "No ProtoSpec generator at $protospec_root." >&2
    echo "Pass --protospec-root." >&2
    exit 1
fi

cd "$protospec_root"
exec uv run python -m protospec_gen.emit_ue --out "$urlab_root" ${check:+$check}
"""


# --------------------------------------------------------------------------- #
# Assembly                                                                     #
# --------------------------------------------------------------------------- #
def generate(root: str | None = None,
             prefix: str = DEFAULT_PREFIX) -> dict[str, str]:
    """{URLab-relative path: content} for every file the UE profile owns."""
    s = UeSchema(load_schema(root), prefix)
    files: dict[str, str] = {}
    for e in s.elements:
        fam = element_family(s, e["name"])
        sub = f"{fam}/" if fam else ""
        files[f"{PUBLIC}/Elements/{sub}Mj{e['name']}.gen.h"] = element_header(s, e)
    files[f"{PUBLIC}/MjElements.gen.h"] = emit_elements_umbrella(s)
    files[f"{PUBLIC}/MjEnums.gen.h"] = emit_enums(s)
    files[f"{PUBLIC}/MjKeywords.gen.h"] = emit_keywords_h(s)
    files[f"{PUBLIC}/MjVisit.gen.h"] = emit_visit(s)
    files[f"{PUBLIC}/MjStorage.gen.h"] = emit_storage(s)
    files[f"{PUBLIC}/MjDefaults.gen.h"] = emit_defaults_h(s)
    files[f"{PUBLIC}/MjDispatch.gen.h"] = emit_dispatch_h(s)
    files[f"{PUBLIC}/MjReflect.gen.h"] = emit_reflect_h(s)
    files[f"{PUBLIC}/MjProfile.gen.h"] = emit_profile(s)
    files[f"{PRIVATE}/MjKeywords.gen.cpp"] = emit_keywords_cpp(s)
    files[f"{PRIVATE}/MjDefaults.gen.cpp"] = emit_defaults_cpp(s)
    files[f"{PRIVATE}/MjDispatch.gen.cpp"] = emit_dispatch_cpp(s)
    files[f"{PRIVATE}/MjReflect.gen.cpp"] = emit_reflect_cpp(s)
    files[f"{TESTS}/MjGenCoverage.gen.cpp"] = emit_coverage(s)
    files["Scripts/regen_ue_profile.ps1"] = emit_regen_ps1()
    files["Scripts/regen_ue_profile.sh"] = emit_regen_sh()
    coverage(s, files)
    lint(files)
    return files


def coverage(s: UeSchema, files: dict[str, str]) -> None:
    """Every element has a class, every attribute a property, every enum a
    UENUM -- read off the schema and checked against the emitted text, so a
    silently dropped element or attribute fails generation rather than the
    build."""
    missing: list[str] = []
    for e in s.elements:
        fam = element_family(s, e["name"])
        sub = f"{fam}/" if fam else ""
        path = f"{PUBLIC}/Elements/{sub}Mj{e['name']}.gen.h"
        text = files.get(path)
        if text is None:
            missing.append(f"element {e['name']}: no header")
            continue
        if f"class URLAB_API {s.cls[e['name']]} :" not in text:
            missing.append(f"element {e['name']}: no UCLASS")
        for _fid, f in s.stored_fields(e):
            member = s.member(e, f)
            if not re.search(rf"^\t{re.escape(stored_type(s, f))} "
                             rf"{re.escape(member)};$", text, re.M):
                missing.append(f"{e['name']}.{f['name']}: no UPROPERTY")
            for verb in ("Get", "Set", "Has"):
                if f"\t{verb}{member}(" not in text.replace("bool ", "\t") and \
                        f"{verb}{member}(" not in text:
                    missing.append(f"{e['name']}.{f['name']}: no {verb}")
        if f"void Visit({s.cls[e['name']]}& Element" not in \
                files[f"{PUBLIC}/MjVisit.gen.h"]:
            missing.append(f"element {e['name']}: no Visit")
        if f"void ApplyDefault({s.cls[e['name']]}& Element)" not in \
                files[f"{PRIVATE}/MjDefaults.gen.cpp"]:
            missing.append(f"element {e['name']}: no ApplyDefault")
    enums_text = files[f"{PUBLIC}/MjEnums.gen.h"]
    for en in s.enums:
        if f"enum class {s.enum[en['name']]} : uint8" not in enums_text:
            missing.append(f"enum {en['name']}: no UENUM")
        for m in en["members"]:
            if f"\t{ident(m['name'])} UMETA" not in enums_text:
                missing.append(f"enum {en['name']}.{m['name']}: no enumerator")
    if missing:
        raise UeError("the emitted profile does not cover the schema:\n  " +
                      "\n  ".join(missing[:40]))


_BP_ON_OPTIONAL = re.compile(
    r"UPROPERTY\([^)]*Blueprint[^)]*\)\s*\n\s*TOptional<")
_REPLICATED = re.compile(r"UPROPERTY\([^)]*Replicated[^)]*\)")
_OPTIONAL_PARAM = re.compile(r"\b(?:Get|Set|Has|Clear)\w+\([^)]*TOptional<")
_DEFAULTED_PARAM = re.compile(r"\b(?:Get|Set|Has|Clear)\w+\([^)]*=[^)]*\)\s*\{")
# FVector joins the storage types here even though nothing stores in it: it is
# the one whose indexed access would compile silently, so it stays rejected.
_INDEXED_FIXED = re.compile(r"\b(?:FVector|" + "|".join(FIXED_TYPES) + r")\s*"
                            r"\w*\s*\[\s*\d")


def lint(files: dict[str, str]) -> None:
    """The hard emitter rules, asserted on the emitted text.

    Each of these is a mistake UHT accepts: a Blueprint specifier on a TOptional
    ships a broken bad_type pin, Replicated is rejected only for some inners, a
    TOptional accessor parameter cannot take a default, and indexed access to a
    fixed-arity value compiles for FVector while transposing every quaternion.
    """
    bad: list[str] = []
    for path, text in files.items():
        if not path.endswith((".h", ".cpp")):
            continue
        if _BP_ON_OPTIONAL.search(text):
            bad.append(f"{path}: a Blueprint specifier on a TOptional UPROPERTY")
        if "Blueprint" in text and "UPROPERTY" in text:
            for line in text.splitlines():
                if line.lstrip().startswith("UPROPERTY(") and \
                        "Blueprint" in line:
                    bad.append(f"{path}: Blueprint specifier on {line.strip()}")
        if _REPLICATED.search(text):
            bad.append(f"{path}: a Replicated UPROPERTY")
        if _OPTIONAL_PARAM.search(text):
            bad.append(f"{path}: a TOptional accessor parameter")
        if _DEFAULTED_PARAM.search(text):
            bad.append(f"{path}: an accessor parameter with a default value")
        if _INDEXED_FIXED.search(text):
            bad.append(f"{path}: indexed access to a fixed-arity vector type")
        if not text.isascii():
            bad.append(f"{path}: non-ASCII bytes (MSVC decodes a BOM-less file "
                       "in the system codepage)")
    if bad:
        raise UeError("generated output violates a hard emitter rule:\n  " +
                      "\n  ".join(sorted(set(bad))))


# --------------------------------------------------------------------------- #
# Driver                                                                       #
# --------------------------------------------------------------------------- #
def urlab_root(explicit: str | None = None) -> str | None:
    """The URLab checkout to emit into, or None with the reason printed by the
    caller. ProtoSpec is usable without URLab, so an absent root is a skip."""
    raw = explicit or os.environ.get(ENV_ROOT)
    if not raw:
        return None
    root = os.path.abspath(os.path.expanduser(raw))
    if not os.path.isdir(os.path.join(root, "Source", "URLab")):
        raise UeError(f"{root} is not a URLab checkout (no Source/URLab)")
    return root


def run(check: bool, out: str | None = None,
        prefix: str = DEFAULT_PREFIX) -> list[str]:
    """Write or verify the UE profile. Returns the stale paths under --check."""
    root = urlab_root(out)
    if root is None:
        print(f"UE profile skipped: no URLab checkout (set ${ENV_ROOT} or "
              "pass --out)")
        return []
    files = generate(prefix=prefix)
    if check:
        stale = []
        for name, content in sorted(files.items()):
            path = os.path.join(root, name)
            if not os.path.exists(path):
                stale.append(f"{name} (missing)")
                continue
            with open(path, "r", encoding="utf-8", newline="") as fh:
                current = fh.read()
            if current.replace("\r\n", "\n") != content:
                stale.append(name)
        if not stale:
            print(f"{root}: UE profile is up to date ({len(files)} files)")
        return stale

    written = 0
    for name, content in sorted(files.items()):
        path = os.path.join(root, name)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(content)
        written += 1
    print(f"wrote {written} UE profile files to {root}")
    return []


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", help=f"URLab checkout root (else ${ENV_ROOT})")
    ap.add_argument("--check", action="store_true",
                    help="verify the checked-in tree is up to date, do not write")
    ap.add_argument("--prefix", default=DEFAULT_PREFIX,
                    help="reflected-type name prefix for every generated type")
    args = ap.parse_args()

    stale = run(check=args.check, out=args.out, prefix=args.prefix)
    if stale:
        sys.stderr.write(
            "the UE profile is out of date; re-run "
            "`Scripts/regen_ue_profile.ps1` (or .sh):\n  "
            + "\n  ".join(stale) + "\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
