"""ProtoSpec C++ emitters: schema AST -> generated C++ object model.

It consumes the AST :mod:`protospec_gen.frontend` builds from upstream's
``src/xml/mjcf.schema`` and emits the generated half of the object model into
``lib/generated/``:

    types.h      element structs, enums, union child-list item wrappers, the
                 ElementType enum, and the Clone/operator== declarations.
    types.cc     deep Clone() and field-wise operator== definitions.
    visit.h      the templated per-element/union Visit(elem, V&&) hook;
                 field-id + child traversal.
    reflect.h    field/child/constraint/element/union descriptor tables (the
                 downstream UE mirroring contract; shape documented in that
                 header).
    reflect.cc   the descriptor table storage and presence/clear thunks.
    keywords.h   enum <-> MJCF keyword string conversion declarations.
    keywords.cc  the keyword tables.
    defaults.h   ApplyDefault(elem) declarations.
    defaults.cc  the IDL `=` defaults applied field-by-field.
    xml_binding.h  per-element MJCF binding table types (attr/alias/child rows).
    xml_binding.cc the binding tables the handwritten reader/writer drive.

Representation decisions:
  * presence: optional element fields are ``ps::opt<T>``; required fields are
    plain ``T``.
  * arrays: fixed ``[N]`` -> ``std::array<T,N>``; range ``[lo..hi]`` ->
    ``ps::InlineVec<T,hi>`` (capacity + filled count); unbounded ``[]`` ->
    ``std::vector<T>``; enum keyword sets (``Enum[]``) -> ``std::vector<Enum>``.
  * refs: ``ps::Ref<Target>`` holding the name string (Target is the element or
    union type, kept as a phantom for type-aware validation/rename).
  * child lists: ``std::vector<std::unique_ptr<Child>>`` (stable identity);
    union child lists: one ordered ``std::vector<UnionAny>`` whose item wrapper
    holds a ``std::variant<std::unique_ptr<Member>...>`` (stable element
    pointers, interleave preserved).
  * identity: every element carries ``ps::SourceLoc loc`` and a monotonic
    ``std::uint64_t serial`` (fresh at construction; Clone re-mints so a clone
    attached into the same Model never duplicates a serial). Neither
    participates in ``operator==`` (they are provenance/identity, not content).

Entry point: ``python -m protospec_gen.emit`` writes the files;
``python -m protospec_gen.emit --check`` regenerates in memory and verifies the
checked-in files are byte-identical. Both also drive the Unreal profile
(:mod:`protospec_gen.emit_ue`), but only when a URLab checkout is locatable, so
one command and one gate cover every emission of the schema.
"""

from __future__ import annotations

import argparse
import os
import sys

from .frontend import load_schema

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT_DIR = os.path.join(ROOT, "lib", "generated")

BANNER = "// Generated by protospec_gen.emit — do not edit."

# C++ keywords / context-sensitive identifiers that cannot be used verbatim as
# member, enumerator, or type identifiers; sanitized by appending '_'.
_CPP_KEYWORDS = frozenset(
    """
    alignas alignof and and_eq asm atomic_cancel atomic_commit atomic_noexcept
    auto bitand bitor bool break case catch char char8_t char16_t char32_t
    class compl concept const consteval constexpr constinit const_cast continue
    co_await co_return co_yield decltype default delete do double dynamic_cast
    else enum explicit export extern false float for friend goto if inline int
    long mutable namespace new noexcept not not_eq nullptr operator or or_eq
    private protected public reflexpr register reinterpret_cast requires return
    short signed sizeof static static_assert static_cast struct switch
    synchronized template this thread_local throw true try typedef typeid
    typename union unsigned using virtual void volatile wchar_t while xor xor_eq
    override final
    """.split()
)

# The front end's primitive vocabulary, mapped to its C++ rendering.
_PRIM_CPP = {
    "int32": "int32_t",
    "uint64": "uint64_t",
    "float": "float",
    "double": "double",
    "bool": "bool",
    "string": "std::string",
}

_CARDINALITY_CPP = {
    "zero_or_more": "ZeroOrMore",
    "zero_or_one": "ZeroOrOne",
    "one": "One",
}

_CONSTRAINT_CPP = {
    "exclusive": "Exclusive",
    "together": "Together",
    "requires": "Requires",
    "oneof": "OneOf",
}

def ident(name: str) -> str:
    """A legal C++ identifier for an IDL name (keyword-safe)."""
    return name + "_" if name in _CPP_KEYWORDS else name


def cpp_str(text: str) -> str:
    """A C++ string literal body (no surrounding quotes) for `text`."""
    return (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )


# --------------------------------------------------------------------------- #
# Schema index                                                                 #
# --------------------------------------------------------------------------- #
class Schema:
    """Indexed view of the JSON AST for the emitters."""

    def __init__(self, doc: dict):
        self.doc = doc
        self.enums = doc["enums"]
        self.unions = doc["unions"]
        self.elements = doc["elements"]
        self.enum_by_name = {e["name"]: e for e in self.enums}
        self.union_by_name = {u["name"]: u for u in self.unions}
        self.element_by_name = {e["name"]: e for e in self.elements}

    def elem_xml(self, elem: dict) -> str:
        return elem["xml"]

    def field_xml(self, f: dict) -> str:
        return f["xml"]

    def child_xml(self, elem: dict, child: dict) -> str:
        """The XML tag routing a child list, empty for a union list (which
        dispatches by member element tag)."""
        return child["tag"]


# --------------------------------------------------------------------------- #
# Type mapping                                                                 #
# --------------------------------------------------------------------------- #
def value_type(t: dict) -> str:
    """C++ type of a field value (before optional wrapping)."""
    kind = t["kind"]
    if kind == "prim":
        base = _PRIM_CPP[t["prim"]]
        arity = t.get("arity")
        if arity is None:
            return base
        if arity["kind"] == "fixed":
            return f"std::array<{base}, {arity['size']}>"
        if arity["kind"] == "range":
            return f"ps::InlineVec<{base}, {arity['max']}>"
        return f"std::vector<{base}>"
    if kind == "ref":
        if t.get("arity") is not None:  # ref<T>[]: space-separated name list
            return f"std::vector<ps::Ref<{t['target']}>>"
        return f"ps::Ref<{t['target']}>"
    if kind == "named":
        name = t["name"]
        if t.get("arity") is not None:  # unbounded keyword set
            return f"std::vector<{name}>"
        return name
    raise AssertionError(f"unhandled type kind {kind!r}")


def stored_type(f: dict) -> str:
    """Storage type of a field: opt-wrapped when optional, else plain."""
    vt = value_type(f["type"])
    return f"ps::opt<{vt}>" if f["optional"] else vt


# --------------------------------------------------------------------------- #
# Default value rendering                                                      #
# --------------------------------------------------------------------------- #
def _fmt_scalar(value, prim: str) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if prim == "string":
        return f'std::string("{cpp_str(str(value))}")'
    if prim in ("int32", "uint64"):
        return str(int(value))
    if prim == "float":
        return f"{float(value)}f"
    return f"{float(value)}"  # double


def render_default(f: dict) -> str:
    """C++ expression for a field's IDL default (the value, not opt-wrapped)."""
    d = f["default"]
    t = f["type"]
    if d["kind"] == "enum":
        return f"{t['name']}::{ident(d['member'])}"
    if d["kind"] == "scalar":
        return _fmt_scalar(d["value"], t["prim"])
    # array default
    base = t["prim"]
    arity = t["arity"]
    elems = ", ".join(_fmt_scalar(v, base) for v in d["values"])
    cpp_base = _PRIM_CPP[base]
    if arity["kind"] == "fixed":
        return f"std::array<{cpp_base}, {arity['size']}>{{{{{elems}}}}}"
    if arity["kind"] == "range":
        return f"ps::InlineVec<{cpp_base}, {arity['max']}>{{{elems}}}"
    return f"std::vector<{cpp_base}>{{{elems}}}"


# --------------------------------------------------------------------------- #
# Reflection classification                                                    #
# --------------------------------------------------------------------------- #
def field_kind(t: dict) -> str:
    kind = t["kind"]
    if kind == "prim":
        return {
            "bool": "Bool",
            "int32": "Int32",
            "uint64": "Uint64",
            "float": "Float",
            "double": "Double",
            "string": "String",
        }[t["prim"]]
    if kind == "ref":
        return "Ref"
    return "Enum"  # named enum (scalar or keyword set)


def field_arity(t: dict) -> tuple[str, int, int]:
    """(ArityKind, min, max) for reflection."""
    arity = t.get("arity")
    if arity is None:
        return ("Scalar", 0, 0)
    if arity["kind"] == "fixed":
        return ("Fixed", arity["size"], arity["size"])
    if arity["kind"] == "range":
        return ("Range", arity["min"], arity["max"])
    return ("Unbounded", 0, 0)


def field_type_name(t: dict) -> str:
    kind = t["kind"]
    if kind == "prim":
        return t["prim"]
    if kind == "ref":
        return t["target"]
    return t["name"]  # named enum


# --------------------------------------------------------------------------- #
# Emitters                                                                     #
# --------------------------------------------------------------------------- #
def emit_types_h(s: Schema) -> str:
    o: list[str] = []
    w = o.append
    w(BANNER)
    w("#ifndef PROTOSPEC_GENERATED_TYPES_H")
    w("#define PROTOSPEC_GENERATED_TYPES_H")
    w("")
    w("#include <array>")
    w("#include <cstdint>")
    w("#include <memory>")
    w("#include <string>")
    w("#include <variant>")
    w("#include <vector>")
    w("")
    w('#include "protospec/core.h"')
    w("")
    w("namespace ps::mjcf {")
    w("")

    # Forward declarations of every element (union item wrappers hold pointers
    # to these, and child lists are vectors of unique_ptr to them).
    w("// Forward declarations.")
    for e in s.elements:
        w(f"struct {e['name']};")
    w("")

    # Enums.
    w("// --- Enums (MJCF keyword tables live in keywords.h) ---")
    for e in s.enums:
        w(f"enum class {e['name']} {{")
        for m in e["members"]:
            w(f"  {ident(m['name'])},")
        w("};")
        w("")

    # Union item wrappers (one ordered heterogeneous child list per union).
    w("// --- Union child-list item wrappers (Section 6 interleave) ---")
    for u in s.unions:
        members = u["members"]
        w(f"struct {u['name']} {{")
        w("  enum class Kind {")
        for m in members:
            w(f"    {m},")
        w("  };")
        variant_alts = ", ".join(f"std::unique_ptr<{m}>" for m in members)
        w(f"  std::variant<{variant_alts}> node;")
        w("  Kind kind() const { return static_cast<Kind>(node.index()); }")
        w("};")
        w("")

    # Element structs.
    w("// --- Elements ---")
    for e in s.elements:
        w(f"struct {e['name']} {{")
        w("  ps::SourceLoc loc;")
        w("  std::uint64_t serial = ps::detail::next_serial();")
        for f in e["fields"]:
            w(f"  {stored_type(f)} {ident(f['name'])} = {{}};")
        for c in e["children"]:
            if c.get("union") is not None:
                w(f"  std::vector<{c['union']}> {ident(c['name'])};")
            else:
                w(
                    f"  std::vector<std::unique_ptr<{c['element']}>> "
                    f"{ident(c['name'])};"
                )
        w("};")
        w("")

    # ElementType enum + kind constant.
    w("// --- Element type ids (reflection / binding) ---")
    w("enum class ElementType {")
    for e in s.elements:
        w(f"  {e['name']},")
    w("};")
    w("")
    w("template <class T> struct element_type_of;")
    for e in s.elements:
        w(
            f"template <> struct element_type_of<{e['name']}> "
            f"{{ static constexpr ElementType value = ElementType::{e['name']}; }};"
        )
    w("")
    w("// The inverse map: the struct an ElementType names. Profile-generic code")
    w("// spells an element by its schema identity rather than by a C++ type, so")
    w("// one algorithm can name `the Geom type` in whichever profile it runs.")
    w("template <ElementType E> struct element_of;")
    for e in s.elements:
        w(
            f"template <> struct element_of<ElementType::{e['name']}> "
            f"{{ using type = {e['name']}; }};"
        )
    w("template <ElementType E> using element_t = typename element_of<E>::type;")
    w("")

    # Clone + operator== declarations (defined in types.cc).
    w("// --- Deep clone + field-wise equality (defined in types.cc) ---")
    for u in s.unions:
        w(f"{u['name']} Clone(const {u['name']}& src);")
        w(
            f"bool operator==(const {u['name']}& a, const {u['name']}& b);"
        )
    for e in s.elements:
        w(f"std::unique_ptr<{e['name']}> Clone(const {e['name']}& src);")
        w(f"bool operator==(const {e['name']}& a, const {e['name']}& b);")
        w(
            f"inline bool operator!=(const {e['name']}& a, const {e['name']}& b) "
            "{ return !(a == b); }"
        )
    w("")

    w("}  // namespace ps::mjcf")
    w("")
    w("#endif  // PROTOSPEC_GENERATED_TYPES_H")
    return "\n".join(o) + "\n"


def _field_eq_expr(f: dict) -> str:
    m = ident(f["name"])
    return f"a.{m} == b.{m}"


def emit_types_cc(s: Schema) -> str:
    o: list[str] = []
    w = o.append
    w(BANNER)
    w('#include "types.h"')
    w("")
    w("#include <type_traits>")
    w("#include <utility>")
    w("#include <variant>")
    w("")
    w("namespace ps::mjcf {")
    w("")

    # Union clone + equality.
    for u in s.unions:
        name = u["name"]
        w(f"{name} Clone(const {name}& src) {{")
        w(f"  {name} out;")
        w("  std::visit(")
        w("      [&](const auto& p) {")
        w("        if (p) out.node = Clone(*p);")
        w("      },")
        w("      src.node);")
        w("  return out;")
        w("}")
        w("")
        w(f"bool operator==(const {name}& a, const {name}& b) {{")
        w("  if (a.node.index() != b.node.index()) return false;")
        w("  return std::visit(")
        w("      [&](const auto& pa) {")
        w(
            "        const auto& pb = "
            "std::get<std::decay_t<decltype(pa)>>(b.node);"
        )
        w("        const bool ha = static_cast<bool>(pa);")
        w("        const bool hb = static_cast<bool>(pb);")
        w("        if (ha != hb) return false;")
        w("        return !ha || (*pa == *pb);")
        w("      },")
        w("      a.node);")
        w("}")
        w("")

    # Element clone + equality.
    for e in s.elements:
        name = e["name"]
        w(f"std::unique_ptr<{name}> Clone(const {name}& src) {{")
        w(f"  auto out = std::make_unique<{name}>();")
        w("  out->loc = src.loc;")
        for f in e["fields"]:
            m = ident(f["name"])
            w(f"  out->{m} = src.{m};")
        for c in e["children"]:
            m = ident(c["name"])
            if c.get("union") is not None:
                w(f"  for (const auto& item : src.{m})")
                w(f"    out->{m}.push_back(Clone(item));")
            else:
                w(f"  out->{m} = ps::PtrVecClone(src.{m});")
        w("  return out;")
        w("}")
        w("")

        w(f"bool operator==(const {name}& a, const {name}& b) {{")
        conds = [_field_eq_expr(f) for f in e["fields"]]
        for c in e["children"]:
            m = ident(c["name"])
            if c.get("union") is not None:
                conds.append(f"a.{m} == b.{m}")
            else:
                conds.append(f"ps::PtrVecEq(a.{m}, b.{m})")
        _emit_bool_and(w, conds)
        w("}")
        w("")

    w("}  // namespace ps::mjcf")
    return "\n".join(o) + "\n"


def _emit_bool_and(w, conds: list[str]) -> None:
    if not conds:
        w("  return true;")
        return
    if len(conds) == 1:
        w(f"  return {conds[0]};")
        return
    w(f"  return {conds[0]} &&")
    for c in conds[1:-1]:
        w(f"         {c} &&")
    w(f"         {conds[-1]};")


def emit_visit_h(s: Schema) -> str:
    o: list[str] = []
    w = o.append
    w(BANNER)
    w("//")
    w("// Generated Visit(elem, V&&) hook: the schema-driven serialize seam. One")
    w("// traversal, N consumers: V receives every field by id + name + typed")
    w("// reference, and every child list. V's expected surface:")
    w("//   template <class T> void field(int id, const char* name, T& value);")
    w("//   template <class T> void child(int id, const char* name,")
    w("//       std::vector<std::unique_ptr<T>>& list);")
    w("//   template <class U> void union_child(int id, const char* name,")
    w("//       std::vector<U>& list);")
    w("// A tree walk is a V whose child/union_child call Visit on each item.")
    w("#ifndef PROTOSPEC_GENERATED_VISIT_H")
    w("#define PROTOSPEC_GENERATED_VISIT_H")
    w("")
    w("#include <utility>")
    w("#include <variant>")
    w("")
    w('#include "types.h"')
    w("")
    w("namespace ps::mjcf {")
    w("")

    def emit_visit(name: str, fields: list[dict], child_kinds: list):
        for const in ("", "const "):
            w(f"template <class V> void Visit({const}{name}& e, V&& v) {{")
            fid = 0
            for f in fields:
                w(f'  v.field({fid}, "{f["name"]}", e.{ident(f["name"])});')
                fid += 1
            cid = 0
            for c in child_kinds:
                if c.get("union") is not None:
                    w(
                        f'  v.union_child({cid}, "{c["name"]}", '
                        f'e.{ident(c["name"])});'
                    )
                else:
                    w(f'  v.child({cid}, "{c["name"]}", e.{ident(c["name"])});')
                cid += 1
            w("  (void)v;")
            w("}")
            w("")

    w("// Union item dispatch: visit the active member element.")
    for u in s.unions:
        for const in ("", "const "):
            w(f"template <class V> void Visit({const}{u['name']}& a, V&& v) {{")
            w("  std::visit(")
            w("      [&](auto& p) {")
            w("        if (p) Visit(*p, v);")
            w("      },")
            w("      a.node);")
            w("}")
            w("")

    w("// Element visitors.")
    for e in s.elements:
        emit_visit(e["name"], e["fields"], e["children"])

    w("}  // namespace ps::mjcf")
    w("")
    w("#endif  // PROTOSPEC_GENERATED_VISIT_H")
    return "\n".join(o) + "\n"


def _element_by_name(s: Schema, name: str) -> dict:
    for e in s.elements:
        if e["name"] == name:
            return e
    raise KeyError(name)


def emit_reflect_h(s: Schema) -> str:
    o: list[str] = []
    w = o.append
    w(BANNER)
    w("//")
    w("// Runtime reflection: static schema description usable without")
    w("// compile-time knowledge of the element structs. This is the contract")
    w("// downstream UE detail-panel mirroring consumes.")
    w("//")
    w("// Shape: every element has an ElementDescriptor carrying its name, XML")
    w("// tag, a contiguous FieldDescriptor[] (one per authored field, in")
    w("// flattened schema order -- the same order and ids the generated Visit")
    w("// uses) and a ChildDescriptor[] (element or union child lists). Each")
    w("// FieldDescriptor states the field's storage kind, element type name")
    w("// (enum/ref-target name for non-primitives), arity bounds, and")
    w("// whether it is optional / has an IDL default. Dynamic value access is")
    w("// the visitor's job (visit.h); reflection adds only presence + clear")
    w("// accessors (present/clear take the element by void* plus a field id).")
    w("// UnionDescriptor lists a union's member element types so a union child")
    w("// list can be walked generically. kFieldCount_<Element> constants pin")
    w("// each table's length for the generated-code self-check.")
    w("#ifndef PROTOSPEC_GENERATED_REFLECT_H")
    w("#define PROTOSPEC_GENERATED_REFLECT_H")
    w("")
    w("#include <cstddef>")
    w("#include <string_view>")
    w("")
    w('#include "types.h"')
    w("")
    w("namespace ps::mjcf::reflect {")
    w("")
    w("enum class FieldKind {")
    w("  Bool, Int32, Uint64, Float, Double, String, Enum, Ref,")
    w("};")
    w("")
    w("enum class ArityKind { Scalar, Fixed, Range, Unbounded };")
    w("")
    w("enum class Cardinality { ZeroOrMore, ZeroOrOne, One };")
    w("")
    w("struct FieldDescriptor {")
    w("  std::string_view name;       // IDL / IR field name")
    w("  std::string_view xml;        // MJCF attribute name")
    w("  std::string_view type_name;  // prim / enum / ref-target name")
    w("  FieldKind kind;")
    w("  ArityKind arity;")
    w("  int arity_min;")
    w("  int arity_max;")
    w("  bool optional;")
    w("  bool has_default;")
    w('  std::string_view target_from;  // dynamic ref: sibling field naming the')
    w('                                 // target type ("" = not a dynamic ref)')
    w("  std::string_view doc;       // one-line field description (schema comment)")
    w("};")
    w("")
    w("struct ChildDescriptor {")
    w("  std::string_view name;    // IR-side child-list field name")
    w("  std::string_view target;  // element name, or union name if is_union")
    w("  bool is_union;")
    w("  Cardinality card;")
    w("};")
    w("")
    w("// A presence constraint over an element's fields, from the schema's")
    w("// exclusive / together / requires / oneof rows. A bundle is complete")
    w("// when every field it names is present; Exclusive admits at most one")
    w("// complete bundle, OneOf at least one, Together all-or-none, and")
    w("// Requires means the first bundle needs the second.")
    w("enum class ConstraintKind { Exclusive, Together, Requires, OneOf };")
    w("")
    w("struct ConstraintBundle {")
    w("  const int* fields;")
    w("  std::size_t field_count;")
    w("};")
    w("")
    w("struct ConstraintDescriptor {")
    w("  ConstraintKind kind;")
    w("  const ConstraintBundle* bundles;")
    w("  std::size_t bundle_count;")
    w("  std::string_view doc;")
    w("};")
    w("")
    w("struct ElementDescriptor {")
    w("  std::string_view name;")
    w("  std::string_view xml;")
    w("  ElementType type;")
    w("  const FieldDescriptor* fields;")
    w("  std::size_t field_count;")
    w("  const ChildDescriptor* children;")
    w("  std::size_t child_count;")
    w("  const ConstraintDescriptor* constraints;")
    w("  std::size_t constraint_count;")
    w("  bool (*present)(const void* elem, int field_id);")
    w("  void (*clear)(void* elem, int field_id);")
    w("};")
    w("")
    w("struct UnionDescriptor {")
    w("  std::string_view name;")
    w("  const ElementType* members;")
    w("  std::size_t member_count;")
    w("};")
    w("")
    w("// Field-count constants (pin each generated table's length).")
    for e in s.elements:
        w(
            f"inline constexpr std::size_t kFieldCount_{e['name']} = "
            f"{len(e['fields'])};"
        )
    w("")
    w("// The element types <default> carries a SAME-TYPE class partial for: the")
    w("// families whose class element has the live element's own type, so the")
    w("// layered class merge applies field-wise. Read off <default>'s child list,")
    w("// excluding the nested-class child and the distinct-partial families")
    w("// (EqualityDefault / TendonDefault), which the merge does not cover.")
    fams = [
        c["element"]
        for c in _element_by_name(s, "Default")["children"]
        if not c["element"].endswith("Default")
    ]
    w("inline constexpr ElementType kDefaultFamilies[] = {")
    for f in fams:
        w(f"    ElementType::{f},")
    w("};")
    w(
        "inline constexpr std::size_t kDefaultFamilyCount = "
        f"{len(fams)};"
    )
    w("")
    w("constexpr bool IsDefaultFamily(ElementType t) {")
    w("  for (ElementType f : kDefaultFamilies)")
    w("    if (f == t) return true;")
    w("  return false;")
    w("}")
    w("")
    w("const ElementDescriptor& Describe(ElementType type);")
    w("const ElementDescriptor* DescribeByName(std::string_view name);")
    w("std::size_t ElementCount();")
    w("const ElementDescriptor& ElementAt(std::size_t index);")
    w("")
    w("const UnionDescriptor& DescribeUnion(std::string_view name);")
    w("std::size_t UnionCount();")
    w("const UnionDescriptor& UnionAt(std::size_t index);")
    w("")
    w("}  // namespace ps::mjcf::reflect")
    w("")
    w("#endif  // PROTOSPEC_GENERATED_REFLECT_H")
    return "\n".join(o) + "\n"


def emit_reflect_cc(s: Schema) -> str:
    o: list[str] = []
    w = o.append
    w(BANNER)
    w('#include "reflect.h"')
    w("")
    w("#include <array>")
    w("#include <iterator>")
    w("#include <string_view>")
    w("#include <unordered_map>")
    w("")
    w("namespace ps::mjcf::reflect {")
    w("namespace {")
    w("")

    # Per-element field tables.
    for e in s.elements:
        name = e["name"]
        fields = e["fields"]
        if fields:
            w(f"constexpr FieldDescriptor kFields_{name}[] = {{")
            for f in fields:
                ak, amin, amax = field_arity(f["type"])
                target_from = f.get("annotations", {}).get("target_from", "")
                w(
                    f'    {{"{f["name"]}", "{s.field_xml(f)}", '
                    f'"{field_type_name(f["type"])}", '
                    f"FieldKind::{field_kind(f['type'])}, "
                    f"ArityKind::{ak}, {amin}, {amax}, "
                    f"{'true' if f['optional'] else 'false'}, "
                    f"{'true' if 'default' in f else 'false'}, "
                    f'"{target_from}", '
                    f'"{cpp_str(f.get("doc", ""))}"}},'
                )
            w("};")
        if e["children"]:
            w(f"constexpr ChildDescriptor kChildren_{name}[] = {{")
            for c in e["children"]:
                is_union = c.get("union") is not None
                target = c["union"] if is_union else c["element"]
                w(
                    f'    {{"{c["name"]}", "{target}", '
                    f"{'true' if is_union else 'false'}, "
                    f"Cardinality::{_CARDINALITY_CPP[c['cardinality']]}}},"
                )
            w("};")
        _emit_constraints(w, s, e)
        w("")

    # Presence + clear thunks.
    for e in s.elements:
        name = e["name"]
        w(f"bool Present_{name}(const void* p, int fid) {{")
        if not e["fields"]:
            w("  (void)p;")
            w("  (void)fid;")
            w("  return false;")
        else:
            w(f"  const auto& e = *static_cast<const {name}*>(p);")
            w("  (void)e;")
            w("  switch (fid) {")
            for i, f in enumerate(e["fields"]):
                m = ident(f["name"])
                if f["optional"]:
                    w(f"    case {i}: return e.{m}.has_value();")
                else:
                    w(f"    case {i}: return true;")
            w("    default: return false;")
            w("  }")
        w("}")
        optional_ids = [i for i, f in enumerate(e["fields"]) if f["optional"]]
        w(f"void Clear_{name}(void* p, int fid) {{")
        if not optional_ids:
            w("  (void)p;")
            w("  (void)fid;")
        else:
            w(f"  auto& e = *static_cast<{name}*>(p);")
            w("  switch (fid) {")
            for i in optional_ids:
                m = ident(e["fields"][i]["name"])
                w(f"    case {i}: e.{m}.reset(); break;")
            w("    default: break;")
            w("  }")
        w("}")
        w("")

    # Union member tables.
    for u in s.unions:
        members = ", ".join(f"ElementType::{m}" for m in u["members"])
        w(f"constexpr ElementType kUnionMembers_{u['name']}[] = {{ {members} }};")
    w("")

    # Element descriptor table.
    w("constexpr ElementDescriptor kElements[] = {")
    for e in s.elements:
        name = e["name"]
        fields = e["fields"]
        children = e["children"]
        constraints = e.get("constraints", [])
        fptr = f"kFields_{name}" if fields else "nullptr"
        cptr = f"kChildren_{name}" if children else "nullptr"
        kptr = f"kConstraints_{name}" if constraints else "nullptr"
        w(
            f'    {{"{name}", "{s.elem_xml(e)}", ElementType::{name}, '
            f"{fptr}, {len(fields)}, {cptr}, {len(children)}, "
            f"{kptr}, {len(constraints)}, "
            f"&Present_{name}, &Clear_{name}}},"
        )
    w("};")
    w("")
    w("constexpr UnionDescriptor kUnions[] = {")
    for u in s.unions:
        w(
            f'    {{"{u["name"]}", kUnionMembers_{u["name"]}, '
            f"{len(u['members'])}}},"
        )
    w("};")
    w("")
    w("const std::unordered_map<std::string_view, const ElementDescriptor*>&")
    w("NameIndex() {")
    w("  static const std::unordered_map<std::string_view,")
    w("                                  const ElementDescriptor*>")
    w("      index = [] {")
    w("        std::unordered_map<std::string_view, const ElementDescriptor*> m;")
    w("        for (const auto& d : kElements) m.emplace(d.name, &d);")
    w("        return m;")
    w("      }();")
    w("  return index;")
    w("}")
    w("")
    w("}  // namespace")
    w("")
    w("const ElementDescriptor& Describe(ElementType type) {")
    w("  return kElements[static_cast<std::size_t>(type)];")
    w("}")
    w("")
    w("const ElementDescriptor* DescribeByName(std::string_view name) {")
    w("  const auto& index = NameIndex();")
    w("  auto it = index.find(name);")
    w("  return it == index.end() ? nullptr : it->second;")
    w("}")
    w("")
    w("std::size_t ElementCount() { return std::size(kElements); }")
    w("")
    w("const ElementDescriptor& ElementAt(std::size_t index) {")
    w("  return kElements[index];")
    w("}")
    w("")
    w("const UnionDescriptor& DescribeUnion(std::string_view name) {")
    w("  for (const auto& u : kUnions)")
    w("    if (u.name == name) return u;")
    w("  return kUnions[0];")
    w("}")
    w("")
    w("std::size_t UnionCount() { return std::size(kUnions); }")
    w("")
    w("const UnionDescriptor& UnionAt(std::size_t index) {")
    w("  return kUnions[index];")
    w("}")
    w("")
    w("}  // namespace ps::mjcf::reflect")
    return "\n".join(o) + "\n"


def _emit_constraints(w, s: Schema, elem: dict) -> None:
    """The element's presence-constraint rows, bundles resolved to field ids."""
    constraints = elem.get("constraints", [])
    if not constraints:
        return
    name = elem["name"]
    by_xml = {f["xml"]: i for i, f in enumerate(elem["fields"])}
    for ci, con in enumerate(constraints):
        for bi, bundle in enumerate(con["bundles"]):
            ids = ", ".join(str(by_xml[a]) for a in bundle)
            w(f"constexpr int kBundle_{name}_{ci}_{bi}[] = {{ {ids} }};")
        w(f"constexpr ConstraintBundle kBundles_{name}_{ci}[] = {{")
        for bi, bundle in enumerate(con["bundles"]):
            w(f"    {{kBundle_{name}_{ci}_{bi}, {len(bundle)}}},")
        w("};")
    w(f"constexpr ConstraintDescriptor kConstraints_{name}[] = {{")
    for ci, con in enumerate(constraints):
        w(
            f"    {{ConstraintKind::{_CONSTRAINT_CPP[con['kind']]}, "
            f"kBundles_{name}_{ci}, {len(con['bundles'])}, "
            f'"{cpp_str(con.get("doc", ""))}"}},'
        )
    w("};")


def emit_keywords_h(s: Schema) -> str:
    o: list[str] = []
    w = o.append
    w(BANNER)
    w("//")
    w("// Enum <-> MJCF keyword string tables (from the IDL enum defs).")
    w("#ifndef PROTOSPEC_GENERATED_KEYWORDS_H")
    w("#define PROTOSPEC_GENERATED_KEYWORDS_H")
    w("")
    w("#include <string_view>")
    w("")
    w('#include "types.h"')
    w("")
    w("namespace ps::mjcf {")
    w("")
    for e in s.enums:
        name = e["name"]
        w(f"std::string_view ToMjcf({name} value);")
        w(f"bool FromMjcf(std::string_view text, {name}& out);")
    w("")
    w("}  // namespace ps::mjcf")
    w("")
    w("#endif  // PROTOSPEC_GENERATED_KEYWORDS_H")
    return "\n".join(o) + "\n"


def emit_keywords_cc(s: Schema) -> str:
    o: list[str] = []
    w = o.append
    w(BANNER)
    w('#include "keywords.h"')
    w("")
    w("namespace ps::mjcf {")
    w("")
    for e in s.enums:
        name = e["name"]
        w(f"std::string_view ToMjcf({name} value) {{")
        w("  switch (value) {")
        for m in e["members"]:
            w(f'    case {name}::{ident(m["name"])}: return "{m["value"]}";')
        w("  }")
        w('  return "";')
        w("}")
        w("")
        w(f"bool FromMjcf(std::string_view text, {name}& out) {{")
        for m in e["members"]:
            w(f'  if (text == "{m["value"]}") {{ out = {name}::{ident(m["name"])};'
              " return true; }")
        w("  return false;")
        w("}")
        w("")
    w("}  // namespace ps::mjcf")
    return "\n".join(o) + "\n"


def emit_defaults_h(s: Schema) -> str:
    o: list[str] = []
    w = o.append
    w(BANNER)
    w("//")
    w("// IDL `=` defaults, applied on request; never silently written.")
    w("// ApplyDefault populates only fields the IDL gives a default; every other")
    w("// presence-tracked field stays unset. HasDefaults() reports whether an")
    w("// element has any (an empty ApplyDefault is still generated for symmetry).")
    w("#ifndef PROTOSPEC_GENERATED_DEFAULTS_H")
    w("#define PROTOSPEC_GENERATED_DEFAULTS_H")
    w("")
    w('#include "types.h"')
    w("")
    w("namespace ps::mjcf {")
    w("")
    for e in s.elements:
        w(f"void ApplyDefault({e['name']}& e);")
    w("")
    w("}  // namespace ps::mjcf")
    w("")
    w("#endif  // PROTOSPEC_GENERATED_DEFAULTS_H")
    return "\n".join(o) + "\n"


def emit_defaults_cc(s: Schema) -> str:
    o: list[str] = []
    w = o.append
    w(BANNER)
    w('#include "defaults.h"')
    w("")
    w("namespace ps::mjcf {")
    w("")
    for e in s.elements:
        name = e["name"]
        w(f"void ApplyDefault({name}& e) {{")
        any_default = False
        for f in e["fields"]:
            if "default" in f:
                any_default = True
                w(f"  e.{ident(f['name'])} = {render_default(f)};")
        if not any_default:
            w("  (void)e;")
        w("}")
        w("")
    w("}  // namespace ps::mjcf")
    return "\n".join(o) + "\n"


# --------------------------------------------------------------------------- #
# XML binding tables (the reader/writer contract)                              #
# --------------------------------------------------------------------------- #
# These describe, per element, exactly what an MJCF reader and writer need and
# nothing they do not: the element's XML tag; every attribute (its XML
# name, the Visit/reflect field id it targets, its storage kind + arity, whether
# it is an angle unit converted deg->rad at IO, whether it is a space-separated
# keyword set, whether it is carried as element text, and the reader handler that
# owns it); every input alias, an attribute accepted on input and folded into a
# sibling field or a child list; and every child list with the XML tag that
# routes it (empty for union lists, which dispatch by member tag). The tables
# are schema-complete: they cover every element, not
# only the families a reader currently handles, so a later family's reader/writer
# needs zero emitter changes -- it consumes the rows already emitted here.
#
# Field ids are the flattened-field indices the generated Visit hook and the
# reflection tables use, so a table-driven reader can set fields by visiting the
# element and matching ids. Children carry a resolved child ElementType (union members
# are recovered through reflect::DescribeUnion) so a reader can decide support
# and construct without a name lookup.


def _attr_fields(elem: dict) -> list[tuple[int, dict]]:
    """(field_id, field) for every field of an element."""
    return list(enumerate(elem["fields"]))


def _field_unit_angle(f: dict) -> bool:
    return f.get("annotations", {}).get("unit") == "angle"


def _field_keyword_set(t: dict) -> bool:
    # An enum reference carrying the unbounded arity is a space-separated keyword
    # set (MapValues), stored as std::vector<Enum>.
    return t["kind"] == "named" and t.get("arity") is not None


def _field_element_text(f: dict) -> bool:
    return "element_text" in f.get("annotations", {})


def _field_resolver(f: dict):
    """The reader handler owning this field's read, or None. A non-empty name
    means the plain attribute read is skipped and the reader's resolver registry
    sets the field instead."""
    return f.get("annotations", {}).get("resolver")


def _input_aliases(elem: dict) -> list[tuple[str, str]]:
    """(alias attr, resolver) for every input-alias attribute of an element: an
    MJCF attribute accepted on input and folded into a sibling field or a child
    list, with no field of its own. The front end resolves these."""
    return [(a["attr"], a["resolver"]) for a in elem.get("input_aliases", [])]


def emit_xml_binding_h(s: Schema) -> str:
    o: list[str] = []
    w = o.append
    w(BANNER)
    w("//")
    w("// Per-element MJCF binding tables: the data a table-driven reader/writer")
    w("// needs, keyed to the generated Visit/reflect field ids. Schema-complete")
    w("// (every element), so a later IO family adds no emitter code -- only the")
    w("// handwritten quirk handlers its elements require. Storage kinds and arity")
    w("// reuse reflect.h's enums.")
    w("#ifndef PROTOSPEC_GENERATED_XML_BINDING_H")
    w("#define PROTOSPEC_GENERATED_XML_BINDING_H")
    w("")
    w("#include <cstddef>")
    w("#include <string_view>")
    w("")
    w('#include "reflect.h"')
    w('#include "types.h"')
    w("")
    w("namespace ps::mjcf::xmlbind {")
    w("")
    w("using reflect::ArityKind;")
    w("using reflect::FieldKind;")
    w("")
    w("// An attribute: an XML attribute bound to one field.")
    w("struct AttrBinding {")
    w("  std::string_view attr;        // MJCF attribute name")
    w("  std::string_view type_name;   // enum / ref-target name (else prim name)")
    w("  int field_id;                 // Visit/reflect flattened field id")
    w("  FieldKind kind;")
    w("  ArityKind arity;")
    w("  int arity_min;")
    w("  int arity_max;")
    w("  bool unit_angle;              // deg->rad at IO (compiler.angle=degree)")
    w("  bool keyword_set;             // space-separated enum keyword set")
    w("  bool element_text;            // carried as element text, not attribute")
    w('  std::string_view resolver;    // parse-end resolver name that canonicalizes')
    w('                                // this field ("" = none). A non-empty name')
    w("                                // means the plain attr read is skipped and")
    w("                                // the reader's resolver registry (keyed by")
    w("                                // this name) sets the field instead; the")
    w("                                // writer still emits it plainly.")
    w("};")
    w("")
    w("// A read-only input-alias attribute: an MJCF attribute")
    w("// accepted on input that is canonicalized into a sibling field at parse end")
    w("// (euler/axisangle/xyaxes/zaxis -> quat; fullinertia -> diaginertia+iquat).")
    w("// It has no field of its own; the reader accepts it (so it is not an unknown")
    w("// attribute) and its resolver names the fold. The writer never emits it.")
    w("struct InputAliasBinding {")
    w("  std::string_view attr;        // MJCF attribute name")
    w("  std::string_view resolver;    // parse-end resolver that folds it")
    w("};")
    w("")
    w("// A child list: its IR name, the XML tag that routes it (empty for a union")
    w("// list, which dispatches by member tag), the target element or union name,")
    w("// and -- for an element list -- the resolved child ElementType.")
    w("struct ChildBinding {")
    w("  std::string_view name;")
    w("  std::string_view tag;")
    w("  std::string_view target;")
    w("  ElementType child_type;   // valid when !is_union")
    w("  bool is_union;")
    w("};")
    w("")
    w("struct ElementBinding {")
    w("  ElementType type;")
    w("  std::string_view tag;")
    w("  const AttrBinding* attrs;")
    w("  std::size_t attr_count;")
    w("  const InputAliasBinding* input_aliases;")
    w("  std::size_t input_alias_count;")
    w("  const ChildBinding* children;")
    w("  std::size_t child_count;")
    w("  // The schema `alias=` target, or empty. An aliased tag is validated")
    w("  // against that element's row, which mjXSchema reaches through its")
    w("  // recursive branch -- so the engine never checks the aliased element's")
    w("  // OWN attributes. A reader that rejects them is stricter than MuJoCo.")
    w("  std::string_view alias;")
    w("};")
    w("")
    w("const ElementBinding& Bind(ElementType type);")
    w("const ElementBinding* BindByTag(std::string_view tag);")
    w("std::size_t BindingCount();")
    w("const ElementBinding& BindingAt(std::size_t index);")
    w("")
    w("}  // namespace ps::mjcf::xmlbind")
    w("")
    w("#endif  // PROTOSPEC_GENERATED_XML_BINDING_H")
    return "\n".join(o) + "\n"


def emit_xml_binding_cc(s: Schema) -> str:
    o: list[str] = []
    w = o.append
    w(BANNER)
    w('#include "xml_binding.h"')
    w("")
    w("#include <array>")
    w("#include <iterator>")
    w("#include <string_view>")
    w("#include <unordered_map>")
    w("")
    w("namespace ps::mjcf::xmlbind {")
    w("namespace {")
    w("")

    for e in s.elements:
        name = e["name"]
        attrs = _attr_fields(e)

        if attrs:
            w(f"constexpr AttrBinding kAttrs_{name}[] = {{")
            for fid, f in attrs:
                t = f["type"]
                ak, amin, amax = field_arity(t)
                w(
                    f'    {{"{s.field_xml(f)}", "{field_type_name(t)}", {fid}, '
                    f"FieldKind::{field_kind(t)}, ArityKind::{ak}, {amin}, {amax}, "
                    f"{'true' if _field_unit_angle(f) else 'false'}, "
                    f"{'true' if _field_keyword_set(t) else 'false'}, "
                    f"{'true' if _field_element_text(f) else 'false'}, "
                    f'"{_field_resolver(f) or ""}"}},'
                )
            w("};")

        aliases = _input_aliases(e)
        if aliases:
            w(f"constexpr InputAliasBinding kInputAliases_{name}[] = {{")
            for attr, resolver in aliases:
                w(f'    {{"{attr}", "{resolver}"}},')
            w("};")

        if e["children"]:
            w(f"constexpr ChildBinding kChildren_{name}[] = {{")
            for c in e["children"]:
                is_union = c.get("union") is not None
                if is_union:
                    target = c["union"]
                    child_type = "ElementType::" + s.elements[0]["name"]
                else:
                    target = c["element"]
                    child_type = f"ElementType::{c['element']}"
                w(
                    f'    {{"{c["name"]}", "{s.child_xml(e, c)}", "{target}", '
                    f"{child_type}, {'true' if is_union else 'false'}}},"
                )
            w("};")
        w("")

    w("constexpr ElementBinding kBindings[] = {")
    for e in s.elements:
        name = e["name"]
        attrs = _attr_fields(e)
        aliases = _input_aliases(e)
        aptr = f"kAttrs_{name}" if attrs else "nullptr"
        iptr = f"kInputAliases_{name}" if aliases else "nullptr"
        cptr = f"kChildren_{name}" if e["children"] else "nullptr"
        w(
            f'    {{ElementType::{name}, "{s.elem_xml(e)}", '
            f"{aptr}, {len(attrs)}, {iptr}, {len(aliases)}, "
            f"{cptr}, {len(e['children'])}, \"{e.get('alias', '')}\"}},"
        )
    w("};")
    w("")
    w("const std::unordered_map<std::string_view, const ElementBinding*>&")
    w("TagIndex() {")
    w("  static const std::unordered_map<std::string_view, const ElementBinding*>")
    w("      index = [] {")
    w("        std::unordered_map<std::string_view, const ElementBinding*> m;")
    w("        for (const auto& b : kBindings) m.emplace(b.tag, &b);")
    w("        return m;")
    w("      }();")
    w("  return index;")
    w("}")
    w("")
    w("}  // namespace")
    w("")
    w("const ElementBinding& Bind(ElementType type) {")
    w("  return kBindings[static_cast<std::size_t>(type)];")
    w("}")
    w("")
    w("const ElementBinding* BindByTag(std::string_view tag) {")
    w("  const auto& index = TagIndex();")
    w("  auto it = index.find(tag);")
    w("  return it == index.end() ? nullptr : it->second;")
    w("}")
    w("")
    w("std::size_t BindingCount() { return std::size(kBindings); }")
    w("")
    w("const ElementBinding& BindingAt(std::size_t index) {")
    w("  return kBindings[index];")
    w("}")
    w("")
    w("}  // namespace ps::mjcf::xmlbind")
    return "\n".join(o) + "\n"


# --------------------------------------------------------------------------- #
# Driver                                                                        #
# --------------------------------------------------------------------------- #
def generate(root: str | None = None) -> dict[str, str]:
    """Return {filename: content} for every generated file."""
    s = Schema(load_schema(root))
    files = {
        "types.h": emit_types_h(s),
        "types.cc": emit_types_cc(s),
        "visit.h": emit_visit_h(s),
        "reflect.h": emit_reflect_h(s),
        "reflect.cc": emit_reflect_cc(s),
        "keywords.h": emit_keywords_h(s),
        "keywords.cc": emit_keywords_cc(s),
        "defaults.h": emit_defaults_h(s),
        "defaults.cc": emit_defaults_cc(s),
        "xml_binding.h": emit_xml_binding_h(s),
        "xml_binding.cc": emit_xml_binding_cc(s),
    }
    return files


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="verify lib/generated/ is up to date, do not write",
    )
    args = ap.parse_args()

    files = generate()

    # The UE profile emits into a URLab checkout rather than into this tree, so
    # it participates in the same gate whenever that checkout is locatable
    # ($PROTOSPEC_URLAB_ROOT) and skips with a stated reason when it is not --
    # ProtoSpec is meant to be usable without URLab.
    from . import emit_ue

    if args.check:
        stale = []
        for name, content in files.items():
            path = os.path.join(OUT_DIR, name)
            if not os.path.exists(path):
                stale.append(f"{name} (missing)")
                continue
            with open(path, "r", encoding="utf-8", newline="") as fh:
                current = fh.read()
            if current.replace("\r\n", "\n") != content:
                stale.append(name)
        stale += ["<urlab>/" + n for n in emit_ue.run(check=True)]
        if stale:
            sys.stderr.write(
                "generated code is out of date; re-run "
                "`python -m protospec_gen.emit`:\n  "
                + "\n  ".join(stale)
                + "\n"
            )
            sys.exit(1)
        print(f"lib/generated/ is up to date ({len(files)} files)")
        return

    os.makedirs(OUT_DIR, exist_ok=True)
    total = 0
    for name, content in files.items():
        path = os.path.join(OUT_DIR, name)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(content)
        total += content.count("\n") + 1
    emit_ue.run(check=False)
    print(f"wrote {len(files)} files to {OUT_DIR} ({total} lines)")


if __name__ == "__main__":
    main()
