# Generated by protospec_gen.emit_ue -- do not edit.
#
# Regenerate URLab's MuJoCo spec profile from the MJCF schema.
#
# The generator lives in the plugin (protospec/), and reads the schema from the
# MuJoCo submodule: a MuJoCo bump moves the grammar and this regenerates against
# it, without a ProtoSpec change dragging MuJoCo's own build along with it.
#
#   .\Scripts\regen_ue_profile.ps1            # rewrite Source/URLab/*/MuJoCo/Gen
#   .\Scripts\regen_ue_profile.ps1 -Check     # fail if it is out of date
[CmdletBinding()]
param(
    [switch]$Check,
    [string]$ProtospecRoot
)
$ErrorActionPreference = "Stop"

$UrlabRoot = Split-Path -Parent $PSScriptRoot
if (-not $ProtospecRoot) {
    $ProtospecRoot = Join-Path $UrlabRoot "protospec"
}
if (-not (Test-Path (Join-Path $ProtospecRoot "protospec_gen"))) {
    throw "No ProtoSpec generator at $ProtospecRoot. Pass -ProtospecRoot."
}

$Args = @("run", "python", "-m", "protospec_gen.emit_ue", "--out", $UrlabRoot)
if ($Check) { $Args += "--check" }

Push-Location $ProtospecRoot
try {
    & uv @Args
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
}
finally {
    Pop-Location
}
