#!/usr/bin/env bash
# Generated by protospec_gen.emit_ue -- do not edit.
#
# Regenerate URLab's MuJoCo spec profile from the MJCF schema.
#
# The generator lives in the plugin (protospec/), and reads the schema from the
# MuJoCo submodule: a MuJoCo bump moves the grammar and this regenerates against
# it, without a ProtoSpec change dragging MuJoCo's own build along with it.
#
#   ./Scripts/regen_ue_profile.sh          # rewrite Source/URLab/*/MuJoCo/Gen
#   ./Scripts/regen_ue_profile.sh --check  # fail if it is out of date
set -euo pipefail

check=""
protospec_root=""
while [ $# -gt 0 ]; do
    case "$1" in
        --check) check="--check"; shift ;;
        --protospec-root) protospec_root="$2"; shift 2 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
urlab_root="$(dirname "$script_dir")"
if [ -z "$protospec_root" ]; then
    protospec_root="$urlab_root/protospec"
fi
if [ ! -d "$protospec_root/protospec_gen" ]; then
    echo "No ProtoSpec generator at $protospec_root." >&2
    echo "Pass --protospec-root." >&2
    exit 1
fi

cd "$protospec_root"
exec uv run python -m protospec_gen.emit_ue --out "$urlab_root" ${check:+$check}
